INSERT INTO ies (nome, uf, municipio) VALUES 
('STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Faculdade Barros Melo Recife', 'PE', 'Recife'),
('FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Faculdade Alpha', 'PE', 'Recife'),
('FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Centro Universitário SATC', 'SC', 'Criciúma'),
('FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Centro Universitário LS', 'DF', 'Brasília'),
('Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Faculdade Santa Teresa', 'AM', 'Manaus'),
('FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Faculdade Life Unic Education', 'SC', 'Joinville'),
('AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Fasul Educacional EaD', 'MG', 'São Lourenço'),
('FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Instituto Una de Itabira', 'MG', 'Itabira'),
('FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador');