INSERT INTO infraestrutura (tipo, quantidade, ies_id) VALUES 
('Pista de atletismo', 1, 3),
('Laboratório de física', 13, 49),
('Laboratório de design gráfico', 7, 73),
('Auditório para eventos culturais', 3, 66),
('Laboratório de física', 10, 77),
('Praça de alimentação', 1, 70),
('Sala de artes marciais', 2, 98),
('Laboratório de prototipagem', 4, 42),
('Lanchonete', 6, 102),
('Laboratório de design gráfico', 4, 51),
('Laboratório de física', 19, 39),
('Biblioteca física', 2, 39),
('Praça de alimentação', 2, 72),
('Biblioteca física', 2, 22),
('Laboratório de arquitetura', 4, 19),
('Piscina olímpica', 2, 82),
('Sala de cinema', 2, 40),
('Laboratório de prototipagem', 3, 17),
('Laboratório de análise de dados', 8, 4),
('Auditório para eventos culturais', 5, 39),
('Laboratório de design gráfico', 5, 13),
('Lanchonete', 8, 47),
('Restaurante universitário', 2, 4),
('Laboratório de idiomas', 10, 78),
('Laboratório de física', 20, 30),
('Incubadora de empresas', 2, 59),
('Laboratório de design gráfico', 2, 73),
('Centro de pesquisa multidisciplinar', 1, 64),
('Praça de alimentação', 1, 6),
('Laboratório de design gráfico', 9, 50),
('Biblioteca física', 1, 87),
('Pista de atletismo', 2, 30),
('Sala de dança', 3, 101),
('Centro cultural', 1, 28),
('Sala de jogos', 2, 32),
('Piscina olímpica', 2, 44),
('Laboratório de informática', 20, 60),
('Sala de dança', 3, 67),
('Quadra de vôlei', 2, 9),
('Sala de cinema', 2, 102),
('Galeria de arte', 2, 26),
('Centro de pesquisa multidisciplinar', 3, 76),
('Sala de jogos', 1, 47),
('Sala de jogos', 1, 97),
('Centro cultural', 1, 64),
('Sala de coworking', 5, 60),
('Centro de pesquisa multidisciplinar', 1, 22),
('Praça de alimentação', 2, 53),
('Lanchonete', 7, 84),
('Sala de aula invertida', 8, 78),
('Restaurante universitário', 5, 59),
('Sala de cinema', 1, 17),
('Laboratório de informática', 40, 88),
('Laboratório maker', 2, 21),
('Quadra de basquete', 5, 9),
('Praça de alimentação', 2, 13),
('Cafeteria', 3, 56),
('Sala de dança', 4, 89),
('Laboratório de prototipagem', 3, 65),
('Quadra de basquete', 4, 3),
('Laboratório de análise de dados', 9, 7),
('Centro de pesquisa multidisciplinar', 3, 96),
('Centro de simulação médica', 2, 38),
('Auditório', 8, 56),
('Biblioteca física', 3, 28),
('Laboratório de inteligência artificial', 3, 91),
('Centro de inovação e startups', 1, 103),
('Biblioteca física', 3, 19),
('Sala de artes marciais', 2, 10),
('Ginásio poliesportivo', 3, 23),
('Academia de ginástica', 2, 56),
('Campo de golfe', 1, 48),
('Laboratório de informática', 13, 62),
('Sala de artes marciais', 1, 54),
('Laboratório de design gráfico', 4, 73),
('Pista de atletismo', 2, 6),
('Sala de aula invertida', 7, 33),
('Sala de artes marciais', 2, 1),
('Parque tecnológico', 1, 33),
('Piscina olímpica', 2, 15),
('Cafeteria', 1, 78),
('Sala de coworking', 9, 102),
('Centro de pesquisa multidisciplinar', 1, 93),
('Laboratório de idiomas', 13, 63),
('Academia de ginástica', 2, 35),
('Laboratório de inteligência artificial', 1, 18),
('Quadra de basquete', 4, 61),
('Sala de aula tradicional', 133, 97),
('Laboratório de realidade virtual e aumentada', 5, 81),
('Sala de aula tradicional', 155, 80),
('Auditório para eventos culturais', 4, 79),
('Sala de artes marciais', 2, 92),
('Sala de artes marciais', 1, 22),
('Laboratório de robótica', 3, 9),
('Praça de alimentação', 2, 76),
('Laboratório de física', 9, 93),
('Arquivo histórico', 2, 27),
('Laboratório de engenharia elétrica', 8, 73),
('Pista de atletismo', 1, 19),
('Biblioteca digital', 2, 5),
('Piscina olímpica', 2, 93),
('Sala de jogos', 3, 95),
('Sala de dança', 2, 63),
('Laboratório de biologia', 17, 20),
('Centro cultural', 1, 12),
('Incubadora de empresas', 2, 19),
('Laboratório de física', 13, 81),
('Lanchonete', 8, 78),
('Laboratório de engenharia mecânica', 3, 32),
('Incubadora de empresas', 2, 71),
('Centro cultural', 1, 10),
('Auditório', 2, 53),
('Quadra de basquete', 4, 45),
('Parque tecnológico', 2, 20),
('Sala de aula tradicional', 298, 55),
('Incubadora de empresas', 2, 83),
('Quadra de vôlei', 5, 53),
('Biblioteca digital', 2, 102),
('Laboratório de realidade virtual e aumentada', 4, 80),
('Quadra de basquete', 5, 3),
('Sala de cinema', 2, 51),
('Centro de simulação médica', 4, 68),
('Sala de cinema', 1, 45),
('Laboratório de engenharia elétrica', 6, 72),
('Cafeteria', 3, 27),
('Ginásio poliesportivo', 2, 69),
('Biblioteca digital', 1, 3),
('Laboratório de química', 4, 31),
('Sala de aula tradicional', 44, 63),
('Quadra de futebol', 5, 14),
('Biblioteca física', 1, 50),
('Laboratório de idiomas', 16, 45),
('Campo de golfe', 1, 46),
('Academia de ginástica', 3, 57),
('Laboratório de informática', 44, 66),
('Laboratório de engenharia mecânica', 8, 23),
('Sala de cinema', 1, 87),
('Sala de jogos', 1, 64),
('Sala de aula invertida', 22, 6),
('Biblioteca digital', 1, 29),
('Laboratório de realidade virtual e aumentada', 5, 79),
('Campo de golfe', 0, 97),
('Pista de atletismo', 1, 69),
('Campo de golfe', 1, 5),
('Restaurante universitário', 2, 17),
('Sala de dança', 2, 78),
('Incubadora de empresas', 2, 31),
('Sala de aula invertida', 14, 93),
('Laboratório de biologia', 15, 7),
('Laboratório de design gráfico', 3, 94),
('Centro de inovação e startups', 1, 45),
('Anfiteatro', 1, 2),
('Ginásio poliesportivo', 2, 80),
('Biblioteca digital', 2, 15),
('Centro de simulação médica', 1, 60),
('Laboratório de arquitetura', 2, 62),
('Laboratório de análise de dados', 3, 55),
('Cafeteria', 4, 12),
('Quadra de futebol', 2, 42),
('Centro de pesquisa multidisciplinar', 1, 42),
('Pista de atletismo', 1, 81),
('Arquivo histórico', 1, 7),
('Laboratório de robótica', 9, 58),
('Anfiteatro', 4, 83),
('Sala de dança', 2, 51),
('Ginásio poliesportivo', 3, 9),
('Restaurante universitário', 4, 64),
('Laboratório de inteligência artificial', 2, 22),
('Centro de simulação médica', 5, 9),
('Piscina olímpica', 2, 37),
('Parque tecnológico', 1, 61),
('Laboratório maker', 5, 67),
('Laboratório de informática', 28, 19),
('Laboratório de design gráfico', 7, 35),
('Quadra de basquete', 3, 43),
('Auditório para eventos culturais', 4, 36),
('Quadra de basquete', 5, 75),
('Ginásio poliesportivo', 3, 53),
('Quadra de basquete', 2, 94),
('Campo de golfe', 1, 17),
('Laboratório de engenharia mecânica', 3, 51),
('Anfiteatro', 3, 92),
('Sala de dança', 1, 13),
('Lanchonete', 10, 33),
('Laboratório de análise de dados', 4, 14),
('Incubadora de empresas', 1, 76),
('Arquivo histórico', 2, 43),
('Incubadora de empresas', 2, 101),
('Sala de jogos', 1, 52),
('Quadra de basquete', 2, 65),
('Laboratório de robótica', 8, 72),
('Laboratório de informática', 46, 71),
('Campo de golfe', 1, 66),
('Sala de aula invertida', 11, 37),
('Laboratório de análise de dados', 4, 71),
('Quadra de basquete', 4, 61),
('Quadra de futebol', 5, 8),
('Laboratório de física', 19, 42),
('Laboratório de engenharia mecânica', 3, 5),
('Laboratório de realidade virtual e aumentada', 2, 65),
('Piscina olímpica', 1, 20),
('Laboratório de prototipagem', 1, 90),
('Sala de jogos', 1, 78),
('Laboratório de engenharia elétrica', 10, 29),
('Sala de aula invertida', 15, 97),
('Centro de inovação e startups', 2, 13),
('Ginásio poliesportivo', 3, 62),
('Sala de artes marciais', 2, 41),
('Sala de aula invertida', 44, 46),
('Incubadora de empresas', 1, 62),
('Laboratório de engenharia mecânica', 5, 41),
('Arquivo histórico', 1, 28),
('Piscina olímpica', 2, 55),
('Sala de cinema', 2, 82),
('Centro de pesquisa multidisciplinar', 3, 96),
('Centro de pesquisa multidisciplinar', 2, 1),
('Lanchonete', 8, 57),
('Praça de alimentação', 2, 30),
('Auditório para eventos culturais', 5, 54),
('Laboratório de realidade virtual e aumentada', 1, 17),
('Laboratório de informática', 38, 5),
('Piscina olímpica', 2, 69),
('Laboratório de biologia', 10, 90),
('Laboratório de arquitetura', 4, 35),
('Galeria de arte', 1, 8),
('Restaurante universitário', 2, 100),
('Laboratório de informática', 28, 17),
('Galeria de arte', 2, 93),
('Laboratório de realidade virtual e aumentada', 4, 99),
('Sala de cinema', 2, 79),
('Incubadora de empresas', 2, 20),
('Sala de artes marciais', 2, 9),
('Lanchonete', 10, 21),
('Laboratório de prototipagem', 2, 72),
('Laboratório maker', 4, 103),
('Sala de coworking', 2, 93),
('Laboratório de idiomas', 10, 79),
('Auditório para eventos culturais', 5, 55),
('Ginásio poliesportivo', 3, 74),
('Laboratório de análise de dados', 4, 94),
('Quadra de basquete', 5, 84),
('Laboratório de biologia', 19, 41),
('Lanchonete', 3, 76),
('Sala de dança', 2, 22),
('Sala de artes marciais', 1, 17),
('Centro de simulação médica', 1, 95),
('Galeria de arte', 1, 24),
('Sala de cinema', 1, 12),
('Laboratório de física', 4, 19),
('Praça de alimentação', 3, 71),
('Laboratório de engenharia mecânica', 6, 45),
('Lanchonete', 10, 23),
('Laboratório de arquitetura', 2, 22),
('Quadra de basquete', 3, 23),
('Biblioteca digital', 1, 51),
('Praça de alimentação', 2, 11),
('Academia de ginástica', 2, 51),
('Sala de coworking', 10, 35),
('Sala de artes marciais', 3, 26),
('Laboratório de robótica', 3, 74),
('Laboratório de arquitetura', 5, 24),
('Centro de simulação médica', 4, 97),
('Sala de aula invertida', 11, 23),
('Sala de dança', 5, 58),
('Laboratório de robótica', 1, 99),
('Laboratório maker', 2, 9),
('Centro de pesquisa multidisciplinar', 2, 33),
('Praça de alimentação', 3, 71),
('Auditório', 1, 93),
('Academia de ginástica', 2, 6),
('Sala de aula tradicional', 127, 23),
('Biblioteca física', 1, 86),
('Laboratório de prototipagem', 2, 58),
('Auditório', 4, 39),
('Restaurante universitário', 2, 87),
('Laboratório de robótica', 10, 34),
('Estúdio de gravação', 1, 88),
('Biblioteca digital', 1, 12),
('Laboratório de análise de dados', 4, 90),
('Arquivo histórico', 2, 99),
('Laboratório de idiomas', 2, 31),
('Incubadora de empresas', 2, 99),
('Pista de atletismo', 2, 60),
('Centro cultural', 1, 51),
('Biblioteca física', 1, 6),
('Biblioteca física', 2, 26),
('Laboratório de inteligência artificial', 3, 48),
('Praça de alimentação', 3, 7),
('Laboratório de design gráfico', 1, 73),
('Laboratório de engenharia elétrica', 8, 22),
('Sala de artes marciais', 2, 86),
('Laboratório de realidade virtual e aumentada', 2, 71),
('Auditório', 9, 45),
('Parque tecnológico', 1, 1),
('Campo de golfe', 1, 87),
('Parque tecnológico', 1, 95),
('Laboratório de engenharia mecânica', 3, 42),
('Sala de jogos', 3, 70),
('Incubadora de empresas', 1, 82),
('Laboratório de engenharia mecânica', 10, 79);