INSERT INTO ies (nome, uf, municipio) VALUES 
('Universidade Federal do Rio de Janeiro', 'RJ', 'Rio de Janeiro'),
('Universidade de São Paulo', 'SP', 'São Paulo'),
('Universidade Federal de Minas Gerais', 'MG', 'Belo Horizonte'),
('FACULDADE DE PALMAS', 'TO', 'Palmas'),
('FACULDADES INTEGRADAS DE PARANAÍBA - FIPAR', 'MS', 'Paranaíba'),
('FACULDADE DO CEFI', 'RS', 'Porto Alegre'),
('Faculdade do Norte de Mato Grosso', 'MT', 'Guarantã do Norte'),
('Faculdade CTA de Nova Lima', 'MG', 'Nova Lima'),
('Centro Universitário Paulistana', 'SP', 'São Paulo'),
('Faculdade SENAI de Construção', 'MS', 'Campo Grande'),
('FACULDADE DO OESTE POTIGUAR', 'RN', 'São Miguel'),
('FACULDADE ATENAS SETE LAGOAS', 'MG', 'Sete Lagoas'),
('FACULDADE CONCEITO EDUCACIONAL', 'PE', 'Arcoverde'),
('Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('FACULDADE DE SUZANO', 'SP', 'Suzano'),
('Afya Faculdade de Ciências Médicas de Itabuna', 'BA', 'Itabuna'),
('Centro de Ensino Superior CESUL', 'PR', 'Francisco Beltrão'),
('FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Faculdade Presidente Antônio Carlos de Uberlândia', 'MG', 'Uberlândia'),
('Faculdade de Ensino Superior de Parnaíba', 'PI', 'Parnaíba'),
('Centro Universitário Metrocamp Wyden', 'SP', 'Campinas'),
('CENTRO UNIVERSITÁRIO ARMANDO ALVARES PENTEADO', 'SP', 'São Paulo'),
('INSIDE - Instituto Superior para Integração, Desenvolvimento e Educação', 'DF', 'Brasília'),
('FACULDADE REGES DE RIBEIRÃO PRETO', 'SP', 'Ribeirão Preto'),
('Escola de Ensino Superior da Fipe', 'SP', 'São Paulo'),
('FACULDADE DE ROLIM DE MOURA', 'RO', 'Rolim de Moura'),
('FACULDADE SANTA CASA', 'BA', 'Salvador'),
('FACULDADE DE TECNOLOGIA ASSESSORITEC', 'SC', 'Joinville'),
('FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('FACULDADE METROPOLITANA DE ANÁPOLIS', 'GO', 'Anápolis'),
('Faculdade Rachel de Queiroz', 'PR', 'Ponta Grossa'),
('Faculdade Metropolitana de Florianópolis', 'SC', 'Florianópolis'),
('FACULDADES INTEGRADAS DE BOTUCATU', 'SP', 'Botucatu'),
('Faculdade de Tecnologia Senac Maringá', 'PR', 'Maringá'),
('FACULDADE ANHANGUERA DE OSASCO', 'SP', 'Osasco'),
('Faculdade Regional do Centro Sul de Sergipe', 'SE', 'Umbaúba'),
('FACULDADE PADRÃO', 'GO', 'Aparecida de Goiânia'),
('UNIVERSIDADE METODISTA DE PIRACICABA', 'SP', 'Piracicaba'),
('FACULDADES INTEGRADAS RIO BRANCO', 'SP', 'São Paulo'),
('Faculdade Estácio do Amapá - Estácio Amapá', 'AP', 'Macapá'),
('FACULDADE SETE LAGOAS', 'MG', 'Sete Lagoas'),
('Faculdade de Tecnologia de Itapetininga - Prof.Antônio Belizandro Barbosa Rezende', 'SP', 'Itapetininga'),
('Faculdade UNÍNTESE', 'RS', 'Santo Ângelo'),
('FACULDADE ROBERTO MIRANDA', 'SP', 'São Paulo'),
('CENTRO UNIVERSITÁRIO DE BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Centro Universitário FUNVIC', 'SP', 'Pindamonhangaba'),
('CENTRO UNIVERSITÁRIO ESPÍRITO-SANTENSE/FAESA', 'ES', 'Vitória'),
('CENTRO UNIVERSITÁRIO CESMAC', 'AL', 'Maceió'),
('FACULDADE METROPOLITANA DO CARIRI', 'CE', 'Crato'),
('CENTRO UNIVERSITÁRIO BARÃO DE MAUÁ', 'SP', 'Ribeirão Preto'),
('UNIVERSIDADE DO OESTE DE SANTA CATARINA', 'SC', 'Joaçaba'),
('FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('UNIVERSIDADE ESTADUAL DO PIAUÍ', 'PI', 'Teresina'),
('Faculdade Menino Deus', 'RS', 'Porto Alegre'),
('FACULDADE CENTRO MATO-GROSSENSE', 'MT', 'Sorriso'),
('FACULDADES FATIFAJAR - FATIFAJAR ARAPOTI', 'PR', 'Arapoti'),
('FACULDADES OSWALDO CRUZ', 'SP', 'São Paulo'),
('ESCOLA SUPERIOR DOM HELDER CÂMARA', 'MG', 'Belo Horizonte'),
('UNIVERSIDADE DO ESTADO DO RIO DE JANEIRO', 'RJ', 'Rio de Janeiro'),
('CENTRO UNIVERSITÁRIO DE PRESIDENTE PRUDENTE', 'SP', 'Presidente Prudente'),
('FACULDADE MILTON CAMPOS', 'MG', 'Nova Lima'),
('FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('FACULDADE DE CIÊNCIAS AGRÁRIAS DE ARARIPINA', 'PE', 'Araripina'),
('INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE MATO GROSSO DO SUL', 'MS', 'Campo Grande'),
('UNIVERSIDADE FEDERAL DE SERGIPE', 'SE', 'São Cristóvão'),
('FACULDADE DE ROSEIRA', 'SP', 'Roseira'),
('Faculdade Metropolitana de Itacoatiara', 'AM', 'Itacoatiara'),
('FACULDADE STBNB', 'PE', 'Recife'),
('Faculdade FaCiencia', 'PR', 'Curitiba'),
('FACULDADE EVANGÉLICA DE TECNOLOGIA, CIÊNCIAS E BIOTECNOLOGIA DA CGADB', 'RJ', 'Rio de Janeiro'),
('FACULDADE PITÁGORAS UNOPAR DE ITAJUBÁ', 'MG', 'Itajubá'),
('FACULDADE DE TECNOLOGIA DE CRUZEIRO DO OESTE', 'PR', 'Cruzeiro do Oeste'),
('Faculdade Alpha', 'PE', 'Recife'),
('Faculdade Atitus Educação Online', 'RS', 'Porto Alegre'),
('Faculdade Multiversa de Palotina', 'PR', 'Palotina'),
('FACULDADE CATEDRAL', 'GO', 'Valparaíso de Goiás'),
('FACULDADE BAHIANA DE ENGENHARIA E CIÊNCIAS SOCIAIS APLICADAS', 'BA', 'Salvador'),
('FACULDADE FASIPE DE RONDONÓPOLIS', 'MT', 'Rondonópolis'),
('FANEESP - FACULDADE NACIONAL DE EDUCAÇÃO E ENSINO SUPERIOR DO PARANÁ', 'PR', 'Araucária'),
('FACULDADE DE TECNOLOGIA DE JAHU', 'SP', 'Jaú'),
('FACULDADE DE EDUCAÇÃO E TECNOLOGIA IRACEMA', 'SP', 'São Paulo'),
('FACULDADE CATÓLICA IMACULADA CONCEIÇÃO DO RECIFE', 'PE', 'Recife'),
('FACULDADE DE CIÊNCIAS DA SAÚDE', 'SE', 'Aracaju'),
('Centro Universitário Católica do Leste de Minas Gerais', 'MG', 'Coronel Fabriciano'),
('Faculdade Uriel de Almeida Leitão', 'MG', 'Caratinga'),
('Centro Universitário - Católica de Santa Catarina em Joinville', 'SC', 'Joinville'),
('Escola Superior de Agronomia de Paraguaçu Paulista', 'SP', 'Paraguaçu Paulista'),
('Faculdade AGES de Jacobina', 'BA', 'Jacobina'),
('CENTRO DE ENSINO SUPERIOR DE BACABEIRA', 'MA', 'Bacabeira'),
('FACULDADE DE MEDICINA ESTÁCIO DE CASTANHAL', 'PA', 'Castanhal'),
('FACULDADE ESTÁCIO DE FLORIANÓPOLIS - ESTÁCIO FLORIANÓPOLIS', 'SC', 'Florianópolis'),
('CENTRO UNIVERSITÁRIO FACOL', 'PE', 'Vitória de Santo Antão'),
('FACULDADE NETWORK', 'SP', 'Nova Odessa'),
('UNIVERSIDADE SANTO AMARO', 'SP', 'São Paulo'),
('CENTRO UNIVERSITÁRIO ANHANGÜERA', 'SP', 'Leme'),
('FACULDADE FLAMINGO', 'SP', 'São Paulo'),
('UNIVERSIDADE FEDERAL DA BAHIA', 'BA', 'Salvador'),
('Faculdade de Tecnologia Sebrae', 'SP', 'São Paulo'),
('FACULDADE DE SANTO ANTONIO DA PLATINA', 'PR', 'Santo Antônio da Platina'),
('FACULDADES INTEGRADAS DOS CAMPOS GERAIS', 'PR', 'Ponta Grossa'),
('Faculdade FABAD', 'SP', 'Pindamonhangaba'),
('FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Faculdade Única de Contagem', 'MG', 'Contagem');
