INSERT INTO acessibilidade (tipo, descricao, nome_ies, uf_ies, municipio_ies) VALUES 
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Acesso facilitado', 'Portas largas e automáticas.', 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Mesa ajustável', 'Mesas reguláveis em altura.', 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Piso tátil', 'Piso em relevo para orientação de deficientes visuais.', 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 'Faculdade Alpha', 'PE', 'Recife'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'Faculdade Alpha', 'PE', 'Recife'),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 'Faculdade Alpha', 'PE', 'Recife'),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Mesa ajustável', 'Mesas reguláveis em altura.', 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Piso tátil', 'Piso em relevo para orientação de deficientes visuais.', 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Mesa ajustável', 'Mesas reguláveis em altura.', 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Salas de descanso', 'Espaço para alunos com condições especiais.', 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Chão antiderrapante', 'Superfícies seguras para circulação.', 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Sinalização de emergência', 'Pontos de evacuação sinalizados.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Mesa ajustável', 'Mesas reguláveis em altura.', 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Piso tátil', 'Piso em relevo para orientação de deficientes visuais.', 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Acesso facilitado', 'Portas largas e automáticas.', 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Materiais em braille', 'Documentos impressos em braille.', 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Acesso facilitado', 'Portas largas e automáticas.', 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Piso tátil', 'Piso em relevo para orientação de deficientes visuais.', 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Salas de descanso', 'Espaço para alunos com condições especiais.', 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Chão antiderrapante', 'Superfícies seguras para circulação.', 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Acesso facilitado', 'Portas largas e automáticas.', 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Sinalização de emergência', 'Pontos de evacuação sinalizados.', 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Acesso facilitado', 'Portas largas e automáticas.', 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'Centro Universitário LS', 'DF', 'Brasília'),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 'Centro Universitário LS', 'DF', 'Brasília'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'Centro Universitário LS', 'DF', 'Brasília'),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Piso tátil', 'Piso em relevo para orientação de deficientes visuais.', 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Salas de descanso', 'Espaço para alunos com condições especiais.', 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Salas de descanso', 'Espaço para alunos com condições especiais.', 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Mesa ajustável', 'Mesas reguláveis em altura.', 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Cabines acústicas', 'Espaços isolados para concentração.', 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Salas de descanso', 'Espaço para alunos com condições especiais.', 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Entrada automática', 'Portas automáticas em áreas comuns.', 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Aplicações offline', 'Apps que funcionam sem internet.', 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Materiais em braille', 'Documentos impressos em braille.', 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha');