INSERT INTO acessibilidade (tipo, descricao, ies_id) VALUES 
('Rampa de Acesso', 'Rampas para acesso ao bloco principal', 1),
('Intérprete de Libras', 'Intérpretes em todas as turmas de alunos PCD', 2),
('Sinalização Tátil', 'Mapas e placas táteis para orientação de deficientes visuais', 3),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 5),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 10),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 84),
('Entrada automática', 'Portas automáticas em áreas comuns.', 58),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 11),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 96),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 68),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 83),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 15),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 91),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 18),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 97),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 83),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 30),
('Chão antiderrapante', 'Superfícies seguras para circulação.', 102),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 49),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 33),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 54),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 38),
('Acesso facilitado', 'Portas largas e automáticas.', 45),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 14),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 85),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 97),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 83),
('Salas de descanso', 'Espaço para alunos com condições especiais.', 58),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 89),
('Chão antiderrapante', 'Superfícies seguras para circulação.', 6),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 98),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 59),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 53),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 23),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 36),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 76),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 16),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 26),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 2),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 4),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 27),
('Acesso facilitado', 'Portas largas e automáticas.', 85),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 33),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 96),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 88),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 88),
('Sinalização de emergência', 'Pontos de evacuação sinalizados.', 38),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 40),
('Cabines acústicas', 'Espaços isolados para concentração.', 75),
('Materiais em braille', 'Documentos impressos em braille.', 55),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 26),
('Aplicações offline', 'Apps que funcionam sem internet.', 70),
('Materiais em braille', 'Documentos impressos em braille.', 35),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 100),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 87),
('Aplicações offline', 'Apps que funcionam sem internet.', 22),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 95),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 28),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 89),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 31),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 44),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 95),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 66),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 83),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 37),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 4),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 17),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 27),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 42),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 89),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 21),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 73),
('Piso tátil', 'Piso em relevo para orientação de deficientes visuais.', 102),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 53),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 94),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 59),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 5),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 94),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 81),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 45),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 18),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 53),
('Cabines acústicas', 'Espaços isolados para concentração.', 5),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 46),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 95),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 93),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 11),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 32),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 99),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 58),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 23),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 77),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 29),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 39),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 23),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 54),
('Cabines acústicas', 'Espaços isolados para concentração.', 77),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 15),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 56),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 10),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 16),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 46),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 95),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 15),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 10),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 66),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 8),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 54),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 82),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 36),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 81),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 67),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 65),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 28),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 13),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 71),
('Acesso facilitado', 'Portas largas e automáticas.', 37),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 5),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 21),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 45),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 60),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 37),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 19),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 19),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 62),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 96),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 45),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 7),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 89),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 43),
('Sinalização de emergência', 'Pontos de evacuação sinalizados.', 73),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 7),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 74),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 98),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 82),
('Acesso facilitado', 'Portas largas e automáticas.', 67),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 88),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 100),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 81),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 75),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 4),
('Entrada automática', 'Portas automáticas em áreas comuns.', 42),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 100),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 68),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 47),
('Materiais em braille', 'Documentos impressos em braille.', 21),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 30),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 79),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 32),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 58),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 103),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 63),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 83),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 3),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 37),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 19),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 63),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 40),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 34),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 68),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 8),
('Materiais em braille', 'Documentos impressos em braille.', 20),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 97),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 95),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 85),
('Assentos preferenciais', 'Locais reservados para PCD em auditórios.', 92),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 42),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 31),
('Libras em eventos', 'Tradução de eventos e palestras para Libras.', 74),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 64),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 38),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 81),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 35),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 52),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 93),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 74),
('Mesa ajustável', 'Mesas reguláveis em altura.', 72),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 41),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 65),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 27),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 46),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 28),
('Aplicação de IA', 'Assistentes virtuais para orientação no campus.', 79),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 54),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 36),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 98),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 59),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 59),
('Mapa em braille', 'Mapas de navegação com relevo em braille.', 64),
('Cabines acústicas', 'Espaços isolados para concentração.', 32),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 96),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 37),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 93),
('Atendimento prioritário', 'Fila especial para atendimento a PCD.', 103),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 62),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 36),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 32),
('Sinalização de emergência', 'Pontos de evacuação sinalizados.', 52),
('Interprete de Libras', 'Serviço de tradução simultânea em Libras.', 45),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 9),
('Acesso facilitado', 'Portas largas e automáticas.', 69),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 99),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 27),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 76),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 10),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 82),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 96),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 63),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 4),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 88),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 62),
('Mesa ajustável', 'Mesas reguláveis em altura.', 94),
('Chão antiderrapante', 'Superfícies seguras para circulação.', 30),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 99),
('Cabines acústicas', 'Espaços isolados para concentração.', 2),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 20),
('Materiais em braille', 'Documentos impressos em braille.', 62),
('Acesso facilitado', 'Portas largas e automáticas.', 58),
('Piso tátil', 'Piso em relevo para orientação de deficientes visuais.', 46),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 70),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 100),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 8),
('Aplicativos acessíveis', 'Apps compatíveis com tecnologias assistivas.', 71),
('Elevador adaptado', 'Elevador com espaço para cadeiras de rodas.', 8),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 7),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 3),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 48),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 73),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 46),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 85),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 2),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 14),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 81),
('Telas ampliadas', 'Displays maiores para melhor leitura.', 50),
('Cadeirantes em esportes', 'Espaços adaptados para esportes paralímpicos.', 81),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 48),
('Banheiro acessível', 'Sanitários adaptados para pessoas com deficiência.', 15),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 57),
('Sinalização sonora', 'Sinais sonoros em cruzamentos e elevadores.', 55),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 80),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 38),
('Cadeiras adaptadas', 'Cadeiras especiais em salas de aula.', 50),
('Rotas acessíveis', 'Caminhos sinalizados e sem obstáculos.', 63),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 95),
('Libras online', 'Atendimento remoto com intérprete de Libras.', 62),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 92),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 100),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 7),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 23),
('Aplicações offline', 'Apps que funcionam sem internet.', 29),
('Chão antiderrapante', 'Superfícies seguras para circulação.', 65),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 44),
('Chão antiderrapante', 'Superfícies seguras para circulação.', 29),
('Barras de apoio', 'Barras instaladas em banheiros e corredores.', 9),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 21),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 9),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 43),
('Wi-Fi acessível', 'Plataformas de autenticação adaptadas.', 5),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 81),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 52),
('Cabines acústicas', 'Espaços isolados para concentração.', 97),
('Sistema de voz', 'Navegação assistida por voz nos prédios.', 70),
('Salas de descanso', 'Espaço para alunos com condições especiais.', 101),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 92),
('Materiais em braille', 'Documentos impressos em braille.', 8),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 92),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 14),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 14),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 7),
('Estacionamento reservado', 'Vagas exclusivas para PCD.', 28),
('Monitores acessíveis', 'Dispositivos interativos em altura adequada.', 95),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 56),
('Monitoramento remoto', 'Câmeras com reconhecimento de movimentos.', 93),
('Rampa de acesso', 'Rampas de concreto em áreas de circulação.', 71),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 87),
('Sinalização de emergência', 'Pontos de evacuação sinalizados.', 18),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 79),
('Sinalização de emergência', 'Pontos de evacuação sinalizados.', 88),
('Audiobooks', 'Livros em áudio para deficientes visuais.', 34),
('Ajuste de fonte', 'Opção para aumentar ou diminuir o tamanho da fonte.', 54),
('Sistemas táteis interativos', 'Quiosques de autoatendimento com interfaces táteis.', 98),
('Controle de contraste', 'Ajuste de contraste nas interfaces digitais.', 77),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 24),
('Mesa ajustável', 'Mesas reguláveis em altura.', 45),
('Plataforma elevatória', 'Plataforma para subir escadas com cadeira de rodas.', 24),
('Placas luminosas', 'Sinalizações com iluminação para deficientes visuais.', 5),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 16),
('Corrimão duplo', 'Corrimão em diferentes alturas para melhor apoio.', 4),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 66),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 56),
('Cursos acessíveis', 'Material didático adaptado e inclusivo.', 69),
('Aplicações offline', 'Apps que funcionam sem internet.', 86),
('Balcões rebaixados', 'Atendimento em balcões de altura reduzida.', 15),
('Amplificador de áudio', 'Sistemas para melhorar a audição em auditórios.', 102),
('Leitor de tela', 'Softwares que leem o conteúdo exibido na tela.', 21),
('Carregadores acessíveis', 'Pontos de carga na altura adequada.', 58),
('Alarme visual', 'Alarmes de incêndio com sinalização visual.', 61),
('E-books acessíveis', 'Livros eletrônicos compatíveis com leitores de tela.', 63),
('Legendas em vídeo', 'Vídeos institucionais com legendas embutidas.', 9),
('Guias rebaixadas', 'Rebaixamento de guias para acessibilidade externa.', 32),
('Sinalização visual', 'Indicadores visuais claros para emergência.', 13),
('Veículos adaptados', 'Transporte interno com acessibilidade.', 25),
('Acesso facilitado', 'Portas largas e automáticas.', 59);
