INSERT INTO docentes (genero, raca_cor, data_nascimento, nacionalidade, formacao, regime_trabalho) VALUES
('Homem transgênero', 'Branca', '1999-2-6', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1990-1-20', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', '1995-5-22', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Outra', '1978-7-11', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1999-2-19', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1970-5-13', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', '1970-6-25', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Amarela', '1970-4-25', 'Nigeriana', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Amarela', '1986-11-19', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1999-8-25', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1973-9-9', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Branca', '1991-6-3', 'Mexicana', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1977-1-13', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1989-5-19', 'Chilena', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1980-3-26', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', '1978-10-18', 'Australiana', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '1980-5-25', 'Espanhola', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', '1977-2-12', 'Francês', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1977-4-8', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1976-10-26', 'Indiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', '1996-2-2', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', '1997-5-10', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1997-6-15', 'Chilena', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Branca', '1983-5-8', 'Alemã', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1972-5-12', 'Russa', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1984-5-20', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Indígena', '1973-12-10', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Amarela', '2000-8-5', 'Alemã', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1998-6-12', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', '1981-8-13', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1999-4-16', 'Espanhola', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1996-11-6', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1978-1-19', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1996-1-7', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1978-2-18', 'Portuguêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1991-10-4', 'Chilena', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', '2000-11-14', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1983-6-4', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Indígena', '1988-6-22', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1980-1-16', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1995-2-20', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Amarela', '1988-1-26', 'Italiana', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1971-11-17', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1972-1-18', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1996-12-25', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', '1998-5-14', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1984-1-9', 'Sul-africana', 'Pós-graduação', 'Tempo Parcial'),
('Homem cisgênero', 'Outra', '1989-1-5', 'Canadense', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Branca', '1994-2-26', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', '1998-6-10', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1982-6-21', 'Japonêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '1970-7-23', 'Russa', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1971-4-2', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', '1971-4-7', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '1982-9-27', 'Canadense', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', '1982-6-4', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1998-8-4', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1987-2-12', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1986-6-18', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1986-11-15', 'Neozelandês', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', '1984-1-8', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Branca', '1992-10-21', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', '1970-1-4', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1996-5-12', 'Nigeriana', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1977-8-2', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1990-5-15', 'Indiana', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Parda', '1982-1-8', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1986-9-22', 'Portuguêsa', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '1978-1-10', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1988-3-14', 'Egípcia', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', '1997-5-4', 'Argentina', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1980-5-20', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1985-10-20', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1986-6-14', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1973-11-10', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', '1984-12-14', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', '1992-6-9', 'Italiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1982-2-17', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '1974-5-5', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', '1991-2-25', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '2000-11-19', 'Canadense', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', '1988-6-14', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Preta', '1976-6-20', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', '1993-10-14', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1999-10-1', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Preta', '1993-9-20', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1994-8-14', 'Japonêsa', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '1996-9-26', 'Argentina', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1997-4-10', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1982-10-3', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', '1997-3-3', 'Canadense', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Preta', '1993-10-14', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1974-6-9', 'Argentina', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', '1977-4-2', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1976-7-19', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1993-1-1', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1990-5-3', 'Japonêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1997-7-26', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', '1973-4-21', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', '1973-9-5', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '1988-8-2', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1991-8-25', 'Mexicana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', '2000-10-9', 'Chinêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '1987-8-21', 'Mexicana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1986-7-9', 'Portuguêsa', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', '1988-5-8', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', '1992-9-19', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '1989-9-8', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', '2000-8-16', 'Indiana', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1978-9-9', 'Alemã', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Parda', '1977-4-27', 'Portuguêsa', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', '1982-3-17', 'Chilena', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Branca', '2000-4-24', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', '1997-2-27', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1992-12-12', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1977-8-26', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', '1979-7-17', 'Neozelandês', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1990-9-8', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1979-10-24', 'Alemã', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', '1984-3-14', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1978-8-28', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Branca', '1993-10-21', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1974-4-11', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Branca', '1975-1-18', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1973-11-19', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', '1981-7-17', 'Neozelandês', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', '1982-3-5', 'Mexicana', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Preta', '2000-2-7', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', '1997-6-4', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1977-5-3', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', '1984-12-21', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', '1984-1-12', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '1972-5-11', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1978-6-8', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Parda', '2000-4-14', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1995-10-3', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1996-1-1', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1987-3-16', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1993-7-25', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Amarela', '1987-7-11', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', '1973-2-28', 'Egípcia', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Outra', '1989-7-2', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '1983-2-18', 'Indiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '1971-11-1', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1993-7-14', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1978-11-24', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1995-6-19', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1986-8-15', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1999-11-19', 'Indiana', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', '1980-9-26', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '1993-3-20', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Indígena', '2000-1-6', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1970-7-17', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Preta', '1992-1-28', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', '1993-8-22', 'Japonêsa', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Amarela', '1971-8-20', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Preta', '1974-1-18', 'Sul-africana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', '1993-1-23', 'Argentina', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1970-12-1', 'Russa', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Outra', '1991-4-11', 'Estadunidense', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', '1990-4-7', 'Alemã', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1990-7-2', 'Sul-africana', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Outra', '1982-1-3', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1980-9-14', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1973-9-27', 'Russa', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1984-3-17', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1982-6-1', 'Sul-africana', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '1972-2-1', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Amarela', '1976-6-22', 'Australiana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1986-8-27', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1997-1-24', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1986-11-14', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1999-4-4', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', '1975-4-14', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Preta', '1985-5-28', 'Neozelandês', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1970-10-16', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1979-4-25', 'Australiana', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1974-4-14', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', '1991-7-10', 'Russa', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Indígena', '1996-6-25', 'Argentina', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', '1990-9-14', 'Espanhola', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1972-3-13', 'Chinêsa', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1981-11-17', 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', '1977-12-2', 'Egípcia', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1992-12-3', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1978-9-18', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', '1984-3-5', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', '1982-7-9', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '1982-2-28', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1989-11-1', 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', '1981-5-12', 'Portuguêsa', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Outra', '1977-6-27', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', '1979-3-20', 'Neozelandês', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1977-3-4', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '2000-6-16', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1990-9-19', 'Indiana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', '1986-12-25', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1978-1-14', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '2000-4-18', 'Espanhola', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1986-11-7', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '1977-1-4', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', '1984-2-12', 'Francês', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '1997-12-8', 'Espanhola', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1990-4-21', 'Chilena', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', '1987-1-5', 'Argentina', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', '1999-12-26', 'Estadunidense', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1999-8-11', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1987-8-26', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Outra', '1974-2-4', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1977-8-3', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', '1994-5-6', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Branca', '1977-3-7', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Branca', '1970-9-22', 'Espanhola', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Preta', '1979-2-25', 'Canadense', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1988-2-4', 'Australiana', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1987-7-21', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1990-3-8', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', '1971-12-27', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Preta', '1996-12-7', 'Australiana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '1990-8-8', 'Egípcia', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1992-7-8', 'Canadense', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Parda', '1990-4-22', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1976-7-10', 'Argentina', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1973-12-21', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1975-2-4', 'Australiana', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', '1990-1-4', 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1985-3-12', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', '1974-7-3', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1971-7-20', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', '1986-3-5', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1997-4-4', 'Mexicana', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1984-11-27', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1993-9-17', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', '1971-10-6', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1970-3-12', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1974-8-14', 'Indiana', 'Pós-graduação', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1987-5-11', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Branca', '1991-7-22', 'Neozelandês', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '1994-1-20', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1987-4-21', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1977-12-6', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Parda', '1986-4-3', 'Nigeriana', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Outra', '2000-11-27', 'Russa', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1984-4-21', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '1980-3-8', 'Estadunidense', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1988-7-16', 'Nigeriana', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Branca', '1981-3-7', 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1970-2-8', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1992-12-24', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Branca', '1976-2-13', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '1980-11-3', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1981-1-25', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1995-7-7', 'Italiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', '1994-11-8', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', '1997-8-28', 'Espanhola', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', '1986-9-14', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1977-12-12', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1976-10-8', 'Neozelandês', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1990-5-16', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '2000-11-15', 'Chilena', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1994-8-13', 'Australiana', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', '1988-3-13', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1982-5-16', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1979-3-18', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', '1976-8-17', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '1985-11-1', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', '1999-5-11', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', '1981-7-26', 'Chilena', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1980-4-12', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1980-5-18', 'Estadunidense', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', '1999-9-25', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1991-8-2', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Preta', '1976-2-6', 'Argentina', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1985-8-4', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1999-6-11', 'Nigeriana', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', '1983-5-15', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1971-9-9', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1991-7-11', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1976-2-13', 'Espanhola', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1994-2-19', 'Francês', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', '1985-8-21', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', '1998-4-23', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1985-1-1', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '2000-4-23', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1998-1-10', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', '1971-10-10', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', '1971-10-23', 'Egípcia', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', '1983-3-27', 'Indiana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1988-7-5', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1973-8-11', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', '1973-3-7', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', '1987-7-3', 'Neozelandês', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1974-3-28', 'Francês', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1985-12-24', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1973-5-19', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1988-5-11', 'Portuguêsa', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1993-12-18', 'Nigeriana', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Preta', '1984-12-1', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1995-5-8', 'Chilena', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1976-10-26', 'Estadunidense', 'Doutorado', 'Tempo Integral'),
('Outro', 'Outra', '1991-11-4', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1978-11-9', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1987-7-14', 'Indiana', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '2000-6-1', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1997-7-2', 'Russa', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', '1996-1-28', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1980-10-14', 'Neozelandês', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', '1982-8-12', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Preta', '1972-7-2', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', '1978-10-14', 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1985-10-10', 'Indiana', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', '1982-6-23', 'Sul-africana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1992-5-7', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', '1977-9-25', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1978-7-19', 'Chinêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', '1982-3-6', 'Estadunidense', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1984-5-6', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', '1991-3-17', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', '1982-11-19', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', '1982-6-26', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', '1986-12-13', 'Espanhola', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', '1991-1-17', 'Espanhola', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', '1992-11-16', 'Portuguêsa', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1987-7-16', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Parda', '1986-7-11', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1984-10-10', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', '1989-1-7', 'Mexicana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1978-3-9', 'Italiana', 'Pós-graduação', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1970-8-25', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', '1970-12-10', 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1985-10-19', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '1984-12-3', 'Neozelandês', 'Pós-graduação', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', '1994-1-1', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1973-2-21', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1982-8-10', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1993-12-26', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1971-7-28', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1992-2-1', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Preta', '1983-3-3', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '2000-4-27', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1979-2-27', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', '1998-5-14', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', '1996-7-11', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1996-2-16', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1999-4-9', 'Mexicana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', '1992-3-11', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1970-4-9', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1982-4-2', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1973-1-21', 'Sul-africana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', '1991-11-8', 'Neozelandês', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', '1978-1-25', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Outro', 'Indígena', '1970-8-10', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', '1983-8-18', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1990-4-19', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1995-9-27', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', '1999-11-7', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1974-12-3', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', '1995-11-13', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1971-10-2', 'Argentina', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1982-7-22', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1998-6-15', 'Francês', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1971-3-19', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1973-6-26', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', '1976-5-22', 'Australiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1970-4-13', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', '1978-11-27', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '1986-5-5', 'Chilena', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1973-10-18', 'Espanhola', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', '1970-4-27', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Preta', '1992-9-15', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', '1999-10-11', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1976-3-21', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', '1994-12-7', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1985-1-8', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '1980-2-8', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '2000-8-17', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1978-10-19', 'Indiana', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', '1971-12-8', 'Argentina', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1976-11-21', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1995-4-14', 'Russa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1978-4-1', 'Italiana', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '2000-7-1', 'Portuguêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', '1983-6-12', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', '1994-12-17', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Parda', '1990-2-8', 'Canadense', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1970-6-22', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1999-5-23', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1991-1-16', 'Indiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', '1999-3-23', 'Portuguêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', '1973-4-16', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1988-6-22', 'Espanhola', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1986-11-14', 'Argentina', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', '1982-3-3', 'Portuguêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1971-8-21', 'Estadunidense', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1976-10-12', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1999-7-4', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', '1980-5-9', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '2000-4-10', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '1986-2-2', 'Estadunidense', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1974-1-12', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1981-3-1', 'Chinêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1971-8-14', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1991-6-15', 'Canadense', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1970-12-18', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1979-10-9', 'Nigeriana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1986-8-11', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1999-12-24', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1982-6-10', 'Neozelandês', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1982-5-21', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Branca', '1999-10-19', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1982-10-14', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1981-6-18', 'Mexicana', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Outra', '1976-9-28', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', '1983-3-11', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1991-8-20', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', '1977-5-16', 'Sul-africana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', '1994-7-28', 'Japonêsa', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1995-11-24', 'Mexicana', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1974-7-24', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1997-1-24', 'Chilena', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1987-6-20', 'Italiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1998-8-17', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', '1992-7-23', 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1983-7-10', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1973-7-5', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', '1999-2-24', 'Argentina', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1989-9-18', 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', '1977-4-14', 'Russa', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1986-5-14', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1993-11-25', 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', '1972-7-26', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', '1975-12-12', 'Japonêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', '1997-9-24', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Parda', '2000-7-16', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1986-12-3', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1984-4-17', 'Indiana', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1974-10-24', 'Espanhola', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1977-5-12', 'Russa', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1974-8-10', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', '1972-2-13', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Indígena', '1980-5-9', 'Italiana', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '2000-3-28', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1984-3-3', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', '1976-3-17', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1979-1-23', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', '1985-10-11', 'Nigeriana', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1985-4-19', 'Espanhola', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1993-1-20', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1999-1-20', 'Indiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1988-9-11', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1977-4-11', 'Neozelandês', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1989-8-19', 'Alemã', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Parda', '1995-7-10', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1981-8-12', 'Chilena', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', '1999-10-6', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', '1997-10-28', 'Francês', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Outra', '1997-6-20', 'Alemã', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1995-3-18', 'Estadunidense', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', '1991-7-9', 'Japonêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1991-12-20', 'Chinêsa', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', '1974-1-14', 'Egípcia', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', '1979-12-17', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Preta', '1994-9-20', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1988-6-24', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1987-11-8', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Branca', '1981-5-18', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1989-6-6', 'Estadunidense', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1972-12-28', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Branca', '1995-1-4', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', '1992-10-26', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1998-2-26', 'Neozelandês', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Branca', '1991-5-2', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Parda', '1993-10-1', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1973-12-25', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1975-12-7', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1974-3-21', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '1981-9-7', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1978-8-13', 'Mexicana', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', '1974-6-27', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', '1971-6-26', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Outra', '1972-9-23', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', '1998-9-1', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1996-1-24', 'Espanhola', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', '1984-11-27', 'Portuguêsa', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', '1995-12-1', 'Neozelandês', 'Doutorado', 'Tempo Integral'),
('Outro', 'Branca', '1997-2-12', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1976-6-1', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '1985-5-8', 'Portuguêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', '1983-7-26', 'Australiana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1984-6-2', 'Sul-africana', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', '1989-9-26', 'Chilena', 'Mestrado', 'Tempo Integral'),
('Outro', 'Branca', '1988-2-28', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Preta', '1985-2-16', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', '1998-9-23', 'Russa', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Branca', '1991-4-17', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', '1996-12-14', 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Outra', '1973-12-16', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1970-9-3', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1998-5-15', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1984-9-17', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', '1975-3-14', 'Chinêsa', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1984-7-5', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1972-7-1', 'Espanhola', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1994-10-7', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '1980-2-13', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1974-6-5', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '1987-4-3', 'Francês', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Outra', '1980-5-7', 'Argentina', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1991-7-17', 'Mexicana', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1983-9-10', 'Alemã', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Indígena', '1973-10-12', 'Mexicana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1985-8-4', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Branca', '2000-8-17', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1999-11-26', 'Sul-africana', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1999-4-4', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Amarela', '1974-3-16', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1973-7-25', 'Francês', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Outra', '2000-9-25', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', '1983-10-19', 'Chinêsa', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Amarela', '1986-1-26', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Indígena', '1978-1-10', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Outro', 'Preta', '1998-4-24', 'Russa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1991-12-21', 'Egípcia', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1983-9-7', 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', '1998-4-19', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Parda', '1981-4-26', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', '1997-7-7', 'Espanhola', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1991-9-17', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1987-4-1', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', '1997-6-11', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1991-8-23', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1991-2-3', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1983-11-28', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1990-6-6', 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Amarela', '1987-11-6', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1999-12-3', 'Italiana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1983-4-8', 'Sul-africana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', '1972-10-23', 'Chilena', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', '1985-10-17', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Parda', '1993-2-3', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', '1975-2-9', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1986-10-17', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', '1980-3-5', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1999-2-16', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Outra', '1971-9-9', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', '1976-6-6', 'Argentina', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Outra', '1991-3-14', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1997-12-25', 'Alemã', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1975-5-2', 'Canadense', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1974-10-19', 'Russa', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', '1978-10-4', 'Indiana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', '1972-8-17', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', '1978-12-8', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '1987-5-19', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '1998-10-26', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1978-7-27', 'Italiana', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', '1972-5-6', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', '1972-11-5', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '2000-3-16', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', '1995-10-23', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', '1995-7-16', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1972-8-24', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Preta', '1976-10-12', 'Italiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1990-4-16', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', '1995-2-20', 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', '1978-12-9', 'Chinêsa', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1976-7-3', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', '1972-11-8', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Preta', '1990-4-28', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1991-3-8', 'Espanhola', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '1994-4-2', 'Indiana', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', '1988-7-17', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1999-11-17', 'Chilena', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', '1975-12-26', 'Chinêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1999-9-20', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', '1982-4-20', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', '1984-10-28', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Outra', '1974-11-16', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '1978-4-3', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1990-8-25', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1979-12-15', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1988-3-20', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1994-4-2', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', '1982-1-27', 'Australiana', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', '1987-2-4', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1988-10-23', 'Argentina', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1981-9-1', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1988-4-12', 'Chinêsa', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1978-1-19', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', '1976-7-28', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', '1971-8-4', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', '2000-9-12', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1984-2-27', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1983-7-27', 'Alemã', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', '1974-1-8', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', '1971-6-7', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1988-1-11', 'Australiana', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1974-1-27', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Parda', '1990-2-24', 'Estadunidense', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Indígena', '1970-5-18', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', '1986-3-3', 'Neozelandês', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Indígena', '1995-11-27', 'Sul-africana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Preta', '1983-7-12', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1971-11-14', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1978-9-24', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1989-10-12', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', '1996-5-28', 'Alemã', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1975-5-26', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', '1972-4-13', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '2000-7-16', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1974-12-7', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1990-5-19', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '1997-6-28', 'Nigeriana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', '1997-3-25', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1972-11-27', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '2000-3-4', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '1979-6-11', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1989-2-27', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1981-4-28', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', '1980-3-18', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Parda', '1985-5-2', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1975-4-24', 'Russa', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1984-3-15', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1973-1-13', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', '1984-12-17', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1977-2-7', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '2000-6-24', 'Neozelandês', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1987-11-10', 'Canadense', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1983-1-11', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1993-7-21', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '1971-2-4', 'Neozelandês', 'Doutorado', 'Tempo Integral'),
('Outro', 'Outra', '1992-12-5', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1983-2-14', 'Egípcia', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1991-2-27', 'Canadense', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Indígena', '1984-2-19', 'Japonêsa', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1993-3-27', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1978-8-24', 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', '1978-10-28', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Preta', '1998-3-15', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1970-4-10', 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1976-4-9', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Branca', '1974-12-9', 'Indiana', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1988-2-4', 'Chinêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1986-5-10', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Branca', '1975-2-7', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1983-12-1', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1989-4-18', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1973-7-5', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1985-9-27', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Preta', '1998-7-16', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', '1989-7-15', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1974-1-15', 'Espanhola', 'Doutorado', 'Tempo Integral'),
('Outro', 'Preta', '1975-10-19', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1990-9-16', 'Japonêsa', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Outra', '1976-7-10', 'Mexicana', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', '1985-4-11', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Parda', '1973-6-14', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1995-5-10', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1999-11-4', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1996-9-26', 'Japonêsa', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', '1998-8-20', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', '1978-3-23', 'Australiana', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1989-5-17', 'Australiana', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1988-7-28', 'Espanhola', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Preta', '1977-12-5', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1982-3-23', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1974-6-23', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem cisgênero', 'Outra', '1996-9-18', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', '1976-3-13', 'Neozelandês', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Parda', '1973-7-15', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1984-7-4', 'Chilena', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1995-2-19', 'Espanhola', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1974-11-28', 'Neozelandês', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1992-11-18', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', '1987-7-21', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Amarela', '1987-3-13', 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1971-7-15', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', '1978-7-12', 'Chinêsa', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', '1998-3-6', 'Canadense', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Parda', '1971-6-25', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1995-1-24', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1996-3-14', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Branca', '2000-8-18', 'Indiana', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1973-1-16', 'Australiana', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1970-6-19', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Parda', '1991-1-4', 'Estadunidense', 'Pós-graduação', 'Tempo Parcial'),
('Outro', 'Indígena', '1970-6-24', 'Nigeriana', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Preta', '1983-5-4', 'Italiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1994-12-23', 'Mexicana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', '1994-6-28', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1971-3-5', 'Australiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1998-7-14', 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', '1998-4-14', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', '1981-12-4', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', '1970-3-27', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1975-1-24', 'Australiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1990-3-19', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', '1972-2-22', 'Chinêsa', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Amarela', '1996-8-20', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', '1987-10-16', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1973-10-15', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', '1982-6-3', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', '1980-1-25', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', '1986-7-10', 'Japonêsa', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', '1984-8-18', 'Alemã', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', '1977-1-24', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1999-5-27', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Branca', '1981-2-15', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1974-2-26', 'Espanhola', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', '1984-12-27', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', '1986-2-2', 'Argentina', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', '1988-8-28', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1982-4-6', 'Argentina', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', '1999-4-2', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Branca', '1977-10-20', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', '1973-11-11', 'Neozelandês', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Outra', '1998-5-28', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1986-10-6', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Preta', '1971-4-10', 'Japonêsa', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', '1985-11-16', 'Portuguêsa', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', '1985-3-25', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '1984-6-3', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', '1992-3-14', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Amarela', '1979-12-4', 'Neozelandês', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1985-3-19', 'Australiana', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Outra', '1997-11-1', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1983-11-10', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1998-12-3', 'Estadunidense', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1980-3-13', 'Indiana', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', '1998-6-8', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1983-9-22', 'Egípcia', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1988-4-5', 'Estadunidense', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Branca', '1981-2-2', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1977-3-16', 'Italiana', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1973-8-10', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1984-4-19', 'Japonêsa', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1988-4-22', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', '1989-9-11', 'Japonêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1993-11-21', 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', '1999-5-21', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', '1972-5-1', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1978-5-9', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', '2000-2-26', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1976-6-3', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1973-5-2', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Branca', '1988-7-25', 'Australiana', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1992-9-5', 'Portuguêsa', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', '1982-5-11', 'Neozelandês', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', '2000-7-24', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1977-9-25', 'Egípcia', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', '1990-11-3', 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', '1986-11-22', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1988-11-28', 'Neozelandês', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', '1979-8-5', 'Australiana', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', '1970-10-14', 'Russa', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1971-3-1', 'Argentina', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1991-3-2', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', '1992-1-28', 'Egípcia', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1997-2-26', 'Indiana', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', '2000-3-15', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', '1993-12-18', 'Chilena', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1981-3-19', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1971-4-24', 'Sul-africana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '1985-3-16', 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', '1995-4-24', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', '1990-2-19', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Parda', '1982-7-12', 'Espanhola', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Branca', '1982-3-4', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1991-8-18', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', '1988-1-6', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Indígena', '1976-10-10', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', '1974-10-24', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Branca', '1995-1-27', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', '1990-1-21', 'Italiana', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1989-11-13', 'Indiana', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1991-1-1', 'Francês', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Branca', '1971-6-27', 'Estadunidense', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Amarela', '2000-2-8', 'Japonêsa', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1978-6-12', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', '1994-11-25', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '1988-10-10', 'Portuguêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1971-1-9', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Outra', '1972-10-27', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Outro', 'Outra', '1970-3-4', 'Francês', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', '1998-2-8', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '1973-11-13', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '1981-8-1', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', '1992-2-15', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1996-11-1', 'Italiana', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Amarela', '1980-6-8', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Branca', '1989-5-8', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1990-10-16', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1988-1-1', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', '1978-7-2', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', '1977-10-7', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1972-3-28', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1986-2-3', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', '1999-1-17', 'Francês', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1971-2-7', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1976-7-7', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1995-5-20', 'Espanhola', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', '1970-10-19', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', '1993-1-7', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1982-10-19', 'Nigeriana', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1998-12-26', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', '1981-5-7', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', '1992-12-10', 'Egípcia', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1994-12-7', 'Espanhola', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1992-2-17', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', '1980-9-25', 'Japonêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1985-11-14', 'Chinêsa', 'Pós-graduação', 'Tempo Parcial'),
('Gênero fluido', 'Branca', '1987-8-6', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1971-8-6', 'Indiana', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', '1970-8-19', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1989-3-26', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', '2000-7-14', 'Nigeriana', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Preta', '2000-12-16', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1992-11-13', 'Estadunidense', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', '1993-4-12', 'Alemã', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', '1970-11-18', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1977-8-28', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1992-12-10', 'Portuguêsa', 'Pós-graduação', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1994-6-18', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', '1971-3-10', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1996-10-3', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1996-9-12', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1976-11-8', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', '1986-6-15', 'Portuguêsa', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1995-8-3', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1978-5-25', 'Canadense', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1983-3-15', 'Alemã', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', '1986-7-10', 'Egípcia', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1992-8-18', 'Portuguêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1970-10-1', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1978-10-12', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1993-7-27', 'Espanhola', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Parda', '1993-6-7', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', '2000-1-2', 'Neozelandês', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Amarela', '1983-1-1', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Preta', '1999-12-24', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', '1974-12-2', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1980-2-9', 'Australiana', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1994-4-8', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', '1998-8-26', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', '1970-5-27', 'Italiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1982-5-22', 'Espanhola', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Parda', '1978-10-26', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', '1970-11-18', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', '1996-11-24', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1980-12-4', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1982-6-21', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Outra', '1994-7-2', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1978-6-5', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', '1991-8-16', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1970-2-24', 'Argentina', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', '1999-6-23', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', '1997-10-10', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1972-8-21', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1996-9-2', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1987-10-24', 'Espanhola', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1972-9-8', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Indígena', '1973-7-18', 'Espanhola', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1989-5-17', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', '1986-2-25', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', '1979-11-15', 'Chinêsa', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1987-4-12', 'Francês', 'Doutorado', 'Tempo Integral'),
('Outro', 'Outra', '1986-7-2', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '2000-8-20', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1972-9-26', 'Indiana', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1979-3-14', 'Russa', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', '1998-5-19', 'Japonêsa', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Preta', '1995-8-6', 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1991-7-17', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1994-12-1', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', '1995-1-6', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1973-7-9', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', '1988-3-11', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1973-7-5', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1994-4-7', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', '1973-12-25', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '1993-12-10', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1984-6-23', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', '1992-4-12', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Amarela', '2000-1-28', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', '1998-4-28', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', '1975-7-20', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Preta', '1975-11-19', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1990-7-20', 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', '1995-5-27', 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Outra', '1990-2-26', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', '1971-6-9', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1980-6-7', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1972-7-4', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Indígena', '1990-8-1', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1992-7-2', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Outra', '1996-10-25', 'Russa', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', '1978-8-6', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1997-6-25', 'Indiana', 'Pós-graduação', 'Tempo Integral'),
('Não-binário', 'Preta', '1983-4-5', 'Francês', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Preta', '2000-1-17', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1990-9-1', 'Francês', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Branca', '1997-2-12', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Amarela', '1996-5-1', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Branca', '1988-12-22', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Preta', '1982-3-12', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', '1979-11-15', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1980-3-4', 'Chinêsa', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Parda', '1999-3-23', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1974-1-22', 'Indiana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1985-8-23', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', '1972-4-8', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', '1978-10-23', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Parda', '1987-6-18', 'Neozelandês', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Parda', '1983-7-22', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', '1996-5-14', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1983-3-5', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', '1999-10-24', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1999-6-13', 'Australiana', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', '1996-10-24', 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', '1972-6-2', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', '1974-7-5', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '1997-7-27', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1993-2-18', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Branca', '1987-7-6', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', '2000-9-21', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', '1985-7-23', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', '1972-9-9', 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', '1975-12-16', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Outra', '1972-11-20', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', '2000-7-12', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', '1974-5-19', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', '1999-2-26', 'Canadense', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', '1972-10-21', 'Chinêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1977-8-16', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', '1970-5-26', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Parda', '1980-10-6', 'Egípcia', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', '1982-2-5', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1978-11-20', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', '1978-10-2', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', '1990-11-1', 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1994-11-28', 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Outro', 'Amarela', '1996-7-16', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', '1980-5-17', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1989-8-15', 'Francês', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Parda', '1974-8-7', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1990-8-6', 'Egípcia', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', '1999-7-11', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1988-1-28', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', '1994-8-12', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1994-3-26', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1988-11-7', 'Estadunidense', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Parda', '1982-9-18', 'Egípcia', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', '1971-4-10', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', '1975-11-12', 'Mexicana', 'Doutorado', 'Tempo Integral'),
('Outro', 'Parda', '1970-7-20', 'Argentina', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '1978-6-25', 'Chilena', 'Pós-graduação', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', '1990-10-16', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', '1982-8-1', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', '1976-11-2', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Outra', '1991-12-11', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', '1995-10-19', 'Brasileira', 'Pós-graduação', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', '1971-10-23', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', '1993-4-10', 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', '1991-2-23', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', '1975-10-26', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', '1990-8-22', 'Alemã', 'Pós-graduação', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', '1988-6-22', 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Preta', '1999-10-24', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', '2000-8-19', 'Neozelandês', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Indígena', '1991-2-2', 'Egípcia', 'Pós-graduação', 'Tempo Parcial'),
('Não-binário', 'Parda', '1985-9-22', 'Egípcia', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', '1999-11-25', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', '1990-4-13', 'Sul-africana', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', '1975-12-18', 'Mexicana', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1980-7-2', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1974-12-7', 'Chilena', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', '1987-5-5', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1998-4-3', 'Nigeriana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1977-8-11', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', '1978-10-1', 'Indiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', '1994-6-25', 'Francês', 'Pós-graduação', 'Tempo Integral'),
('Homem transgênero', 'Branca', '1985-6-13', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Outro', 'Amarela', '1993-9-11', 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', '1974-6-24', 'Canadense', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', '1995-10-20', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', '1996-3-27', 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', '1989-10-17', 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', '1990-7-18', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', '1970-12-10', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Outra', '1972-7-28', 'Brasileira', 'Pós-graduação', 'Tempo Integral'),
('Gênero fluido', 'Parda', '1983-12-7', 'Chinêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', '1996-12-7', 'Brasileira', 'Pós-graduação', 'Dedicação Exclusiva'),
('Outro', 'Amarela', '1982-9-2', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', '1987-7-27', 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Parda', '1981-11-22', 'Portuguêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', '1970-10-28', 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Preta', '1972-1-19', 'Espanhola', 'Pós-graduação', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', '1995-9-10', 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', '1979-11-24', 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', '1977-7-16', 'Brasileira', 'Mestrado', 'Tempo Parcial');