INSERT INTO discentes (genero, raca_cor, idade, nacionalidade, pcd) VALUES
('Feminino', 'Parda', 22, 'Brasileira', TRUE),
('Masculino', 'Branco', 23, 'Brasileira', FALSE),
('Feminino', 'Indígena', 20, 'Brasileira', FALSE),
('Homem cisgênero', 'Parda', 29, 'Espanhola', False),
('Homem transgênero', 'Parda', 28, 'Brasileira', False),
('Mulher cisgênero', 'Indígena', 21, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 20, 'Nigeriana', True),
('Mulher cisgênero', 'Preta', 24, 'Canadense', True),
('Gênero fluido', 'Indígena', 20, 'Australiana', True),
('Mulher cisgênero', 'Amarela', 28, 'Brasileira', True),
('Outro', 'Indígena', 24, 'Brasileira', True),
('Mulher transgênero', 'Outra', 30, 'Sul-africana', True),
('Gênero fluido', 'Outra', 17, 'Brasileira', True),
('Homem transgênero', 'Indígena', 22, 'Brasileira', True),
('Gênero fluido', 'Branca', 19, 'Brasileira', True),
('Gênero fluido', 'Branca', 23, 'Estadunidense', True),
('Não-binário', 'Preta', 24, 'Indiana', True),
('Gênero fluido', 'Parda', 24, 'Brasileira', True),
('Gênero fluido', 'Amarela', 28, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 28, 'Estadunidense', True),
('Homem transgênero', 'Branca', 17, 'Brasileira', False),
('Não-binário', 'Indígena', 22, 'Estadunidense', True),
('Mulher transgênero', 'Outra', 22, 'Brasileira', True),
('Não-binário', 'Indígena', 18, 'Australiana', True),
('Homem transgênero', 'Amarela', 22, 'Espanhola', True),
('Mulher transgênero', 'Preta', 17, 'Brasileira', True),
('Homem transgênero', 'Preta', 26, 'Neozelandês', True),
('Homem cisgênero', 'Parda', 26, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 16, 'Japonêsa', True),
('Gênero fluido', 'Amarela', 16, 'Canadense', True),
('Homem transgênero', 'Amarela', 21, 'Brasileira', False),
('Outro', 'Outra', 17, 'Brasileira', True),
('Mulher transgênero', 'Parda', 28, 'Brasileira', True),
('Homem cisgênero', 'Outra', 25, 'Russa', False),
('Mulher transgênero', 'Branca', 17, 'Nigeriana', True),
('Mulher transgênero', 'Amarela', 27, 'Espanhola', True),
('Mulher transgênero', 'Outra', 27, 'Brasileira', True),
('Não-binário', 'Preta', 28, 'Brasileira', True),
('Mulher transgênero', 'Parda', 16, 'Sul-africana', True),
('Gênero fluido', 'Branca', 16, 'Brasileira', True),
('Não-binário', 'Preta', 23, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 25, 'Brasileira', False),
('Gênero fluido', 'Preta', 20, 'Brasileira', True),
('Não-binário', 'Preta', 26, 'Australiana', True),
('Não-binário', 'Outra', 18, 'Neozelandês', True),
('Não-binário', 'Parda', 25, 'Italiana', True),
('Homem transgênero', 'Outra', 26, 'Brasileira', True),
('Gênero fluido', 'Branca', 24, 'Brasileira', True),
('Gênero fluido', 'Preta', 29, 'Brasileira', True),
('Homem transgênero', 'Indígena', 17, 'Chilena', True),
('Outro', 'Parda', 26, 'Brasileira', True),
('Outro', 'Branca', 20, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 24, 'Sul-africana', True),
('Outro', 'Parda', 28, 'Brasileira', True),
('Homem cisgênero', 'Parda', 25, 'Argentina', True),
('Não-binário', 'Preta', 30, 'Brasileira', True),
('Homem transgênero', 'Parda', 17, 'Brasileira', True),
('Não-binário', 'Parda', 24, 'Brasileira', False),
('Homem transgênero', 'Branca', 21, 'Portuguêsa', True),
('Mulher transgênero', 'Outra', 17, 'Brasileira', True),
('Outro', 'Outra', 28, 'Indiana', True),
('Homem transgênero', 'Amarela', 23, 'Brasileira', True),
('Gênero fluido', 'Amarela', 24, 'Brasileira', False),
('Mulher cisgênero', 'Branca', 20, 'Canadense', True),
('Mulher transgênero', 'Indígena', 27, 'Brasileira', True),
('Mulher cisgênero', 'Preta', 19, 'Brasileira', True),
('Não-binário', 'Branca', 29, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 24, 'Brasileira', True),
('Homem cisgênero', 'Branca', 30, 'Egípcia', True),
('Mulher cisgênero', 'Preta', 17, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 17, 'Brasileira', False),
('Mulher cisgênero', 'Branca', 29, 'Alemã', True),
('Gênero fluido', 'Outra', 30, 'Brasileira', True),
('Mulher transgênero', 'Preta', 16, 'Nigeriana', False),
('Homem cisgênero', 'Outra', 24, 'Francês', True),
('Gênero fluido', 'Indígena', 25, 'Brasileira', True),
('Não-binário', 'Amarela', 28, 'Brasileira', True),
('Homem transgênero', 'Amarela', 23, 'Brasileira', True),
('Não-binário', 'Parda', 30, 'Brasileira', True),
('Homem transgênero', 'Branca', 21, 'Sul-africana', True),
('Mulher transgênero', 'Parda', 17, 'Brasileira', True),
('Gênero fluido', 'Branca', 21, 'Alemã', True),
('Outro', 'Indígena', 29, 'Chilena', True),
('Mulher transgênero', 'Preta', 24, 'Brasileira', True),
('Gênero fluido', 'Outra', 29, 'Brasileira', True),
('Gênero fluido', 'Amarela', 17, 'Russa', True),
('Mulher cisgênero', 'Outra', 24, 'Brasileira', True),
('Homem transgênero', 'Branca', 23, 'Australiana', False),
('Homem cisgênero', 'Parda', 20, 'Indiana', True),
('Outro', 'Branca', 25, 'Chilena', True),
('Não-binário', 'Indígena', 29, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 19, 'Brasileira', True),
('Gênero fluido', 'Indígena', 23, 'Brasileira', True),
('Homem cisgênero', 'Outra', 20, 'Russa', True),
('Homem cisgênero', 'Parda', 30, 'Brasileira', True),
('Mulher transgênero', 'Amarela', 27, 'Brasileira', True),
('Mulher cisgênero', 'Preta', 28, 'Brasileira', True),
('Gênero fluido', 'Indígena', 28, 'Russa', True),
('Mulher cisgênero', 'Outra', 28, 'Argentina', True),
('Mulher cisgênero', 'Outra', 26, 'Brasileira', True),
('Homem transgênero', 'Amarela', 19, 'Canadense', True),
('Mulher cisgênero', 'Preta', 25, 'Sul-africana', True),
('Gênero fluido', 'Preta', 27, 'Brasileira', False),
('Homem transgênero', 'Branca', 18, 'Chilena', True),
('Mulher cisgênero', 'Branca', 24, 'Argentina', True),
('Outro', 'Outra', 16, 'Australiana', True),
('Não-binário', 'Amarela', 26, 'Canadense', False),
('Não-binário', 'Amarela', 27, 'Australiana', True),
('Homem cisgênero', 'Outra', 30, 'Brasileira', True),
('Homem cisgênero', 'Outra', 21, 'Brasileira', True),
('Outro', 'Preta', 16, 'Brasileira', True),
('Não-binário', 'Branca', 18, 'Indiana', False),
('Homem transgênero', 'Indígena', 21, 'Argentina', True),
('Mulher cisgênero', 'Indígena', 17, 'Brasileira', False),
('Mulher transgênero', 'Outra', 29, 'Neozelandês', False),
('Mulher transgênero', 'Parda', 22, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 21, 'Brasileira', False),
('Mulher transgênero', 'Preta', 20, 'Brasileira', False),
('Mulher cisgênero', 'Preta', 18, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 25, 'Brasileira', True),
('Não-binário', 'Branca', 23, 'Brasileira', True),
('Outro', 'Parda', 30, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 19, 'Brasileira', True),
('Outro', 'Indígena', 24, 'Mexicana', True),
('Mulher transgênero', 'Preta', 20, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 18, 'Neozelandês', True),
('Não-binário', 'Outra', 17, 'Brasileira', True),
('Homem transgênero', 'Branca', 28, 'Neozelandês', True),
('Mulher cisgênero', 'Parda', 25, 'Brasileira', True),
('Não-binário', 'Outra', 21, 'Brasileira', True),
('Homem transgênero', 'Parda', 19, 'Argentina', True),
('Homem transgênero', 'Preta', 19, 'Russa', True),
('Gênero fluido', 'Indígena', 24, 'Portuguêsa', True),
('Mulher cisgênero', 'Outra', 21, 'Russa', False),
('Não-binário', 'Amarela', 30, 'Brasileira', True),
('Gênero fluido', 'Branca', 27, 'Argentina', False),
('Mulher cisgênero', 'Amarela', 17, 'Australiana', True),
('Mulher transgênero', 'Parda', 17, 'Brasileira', True),
('Gênero fluido', 'Parda', 25, 'Brasileira', True),
('Homem transgênero', 'Outra', 17, 'Sul-africana', True),
('Homem transgênero', 'Parda', 18, 'Brasileira', True),
('Outro', 'Outra', 26, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 23, 'Brasileira', True),
('Homem transgênero', 'Branca', 30, 'Brasileira', False),
('Mulher cisgênero', 'Branca', 26, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 19, 'Mexicana', True),
('Mulher transgênero', 'Branca', 17, 'Brasileira', True),
('Homem transgênero', 'Parda', 25, 'Brasileira', True),
('Não-binário', 'Parda', 26, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 17, 'Alemã', False),
('Homem cisgênero', 'Branca', 20, 'Brasileira', True),
('Não-binário', 'Preta', 25, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 24, 'Mexicana', True),
('Homem cisgênero', 'Branca', 26, 'Brasileira', True),
('Não-binário', 'Branca', 18, 'Francês', True),
('Outro', 'Outra', 20, 'Brasileira', True),
('Gênero fluido', 'Branca', 18, 'Brasileira', True),
('Mulher transgênero', 'Amarela', 30, 'Japonêsa', True),
('Homem transgênero', 'Branca', 16, 'Portuguêsa', True),
('Mulher cisgênero', 'Preta', 16, 'Brasileira', True),
('Homem transgênero', 'Parda', 22, 'Brasileira', True),
('Outro', 'Outra', 19, 'Brasileira', True),
('Mulher transgênero', 'Branca', 21, 'Brasileira', True),
('Homem cisgênero', 'Parda', 16, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 24, 'Brasileira', True),
('Mulher transgênero', 'Parda', 25, 'Estadunidense', True),
('Homem cisgênero', 'Branca', 25, 'Brasileira', True),
('Homem transgênero', 'Amarela', 26, 'Brasileira', True),
('Outro', 'Amarela', 24, 'Brasileira', True),
('Gênero fluido', 'Branca', 18, 'Canadense', True),
('Homem cisgênero', 'Outra', 24, 'Brasileira', False),
('Mulher transgênero', 'Branca', 28, 'Chilena', True),
('Gênero fluido', 'Branca', 20, 'Alemã', True),
('Homem transgênero', 'Preta', 21, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 23, 'Brasileira', True),
('Não-binário', 'Branca', 26, 'Brasileira', True),
('Mulher transgênero', 'Preta', 16, 'Brasileira', True),
('Não-binário', 'Amarela', 24, 'Brasileira', False),
('Mulher cisgênero', 'Parda', 22, 'Indiana', False),
('Gênero fluido', 'Parda', 23, 'Brasileira', True),
('Mulher transgênero', 'Branca', 21, 'Canadense', True),
('Homem transgênero', 'Outra', 23, 'Brasileira', True),
('Gênero fluido', 'Branca', 21, 'Brasileira', True),
('Homem transgênero', 'Preta', 29, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 29, 'Brasileira', True),
('Gênero fluido', 'Indígena', 29, 'Nigeriana', True),
('Mulher cisgênero', 'Amarela', 19, 'Brasileira', False),
('Homem cisgênero', 'Indígena', 23, 'Russa', True),
('Mulher cisgênero', 'Amarela', 25, 'Australiana', True),
('Mulher transgênero', 'Branca', 19, 'Brasileira', True),
('Gênero fluido', 'Preta', 30, 'Francês', True),
('Mulher cisgênero', 'Indígena', 18, 'Brasileira', True),
('Homem cisgênero', 'Parda', 25, 'Brasileira', True),
('Não-binário', 'Indígena', 18, 'Espanhola', False),
('Homem transgênero', 'Branca', 21, 'Nigeriana', True),
('Homem cisgênero', 'Preta', 19, 'Espanhola', True),
('Outro', 'Outra', 18, 'Brasileira', True),
('Não-binário', 'Parda', 26, 'Italiana', True),
('Homem transgênero', 'Preta', 16, 'Russa', True),
('Outro', 'Branca', 26, 'Chinêsa', True),
('Mulher transgênero', 'Parda', 24, 'Brasileira', True),
('Outro', 'Outra', 22, 'Chinêsa', True),
('Não-binário', 'Amarela', 26, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 18, 'Argentina', True),
('Outro', 'Parda', 29, 'Canadense', True),
('Mulher transgênero', 'Indígena', 16, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 22, 'Brasileira', True),
('Homem transgênero', 'Branca', 22, 'Brasileira', False),
('Outro', 'Amarela', 22, 'Portuguêsa', True),
('Outro', 'Amarela', 19, 'Egípcia', True),
('Mulher transgênero', 'Branca', 29, 'Brasileira', False),
('Homem transgênero', 'Preta', 17, 'Indiana', True),
('Homem transgênero', 'Preta', 19, 'Brasileira', True),
('Gênero fluido', 'Parda', 18, 'Chilena', True),
('Mulher cisgênero', 'Outra', 16, 'Brasileira', True),
('Gênero fluido', 'Parda', 16, 'Brasileira', False),
('Outro', 'Branca', 28, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 30, 'Brasileira', True),
('Gênero fluido', 'Parda', 21, 'Brasileira', True),
('Mulher transgênero', 'Preta', 19, 'Brasileira', True),
('Gênero fluido', 'Indígena', 24, 'Australiana', True),
('Mulher cisgênero', 'Amarela', 28, 'Brasileira', True),
('Homem transgênero', 'Indígena', 17, 'Brasileira', True),
('Mulher transgênero', 'Preta', 19, 'Egípcia', True),
('Homem transgênero', 'Indígena', 17, 'Chilena', True),
('Mulher transgênero', 'Amarela', 27, 'Brasileira', True),
('Outro', 'Parda', 19, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 23, 'Brasileira', True),
('Gênero fluido', 'Branca', 18, 'Italiana', True),
('Mulher transgênero', 'Outra', 30, 'Italiana', True),
('Não-binário', 'Indígena', 16, 'Brasileira', True),
('Outro', 'Parda', 17, 'Portuguêsa', True),
('Homem transgênero', 'Branca', 20, 'Chilena', True),
('Não-binário', 'Preta', 19, 'Brasileira', False),
('Homem transgênero', 'Parda', 16, 'Brasileira', True),
('Mulher transgênero', 'Preta', 20, 'Italiana', True),
('Homem cisgênero', 'Preta', 19, 'Brasileira', False),
('Homem transgênero', 'Indígena', 24, 'Mexicana', True),
('Mulher transgênero', 'Parda', 19, 'Brasileira', True),
('Não-binário', 'Amarela', 29, 'Chilena', True),
('Homem cisgênero', 'Indígena', 26, 'Brasileira', True),
('Homem cisgênero', 'Branca', 24, 'Brasileira', True),
('Outro', 'Indígena', 21, 'Indiana', True),
('Não-binário', 'Indígena', 24, 'Brasileira', True),
('Homem transgênero', 'Branca', 23, 'Brasileira', True),
('Não-binário', 'Indígena', 30, 'Brasileira', True),
('Homem transgênero', 'Preta', 22, 'Francês', True),
('Outro', 'Preta', 25, 'Indiana', True),
('Mulher transgênero', 'Indígena', 16, 'Portuguêsa', True),
('Mulher cisgênero', 'Outra', 18, 'Sul-africana', True),
('Homem transgênero', 'Indígena', 27, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 17, 'Brasileira', False),
('Homem transgênero', 'Indígena', 21, 'Egípcia', True),
('Não-binário', 'Amarela', 27, 'Nigeriana', True),
('Homem cisgênero', 'Parda', 18, 'Brasileira', True),
('Outro', 'Indígena', 26, 'Brasileira', False),
('Não-binário', 'Outra', 28, 'Brasileira', True),
('Mulher transgênero', 'Outra', 22, 'Brasileira', True),
('Outro', 'Branca', 27, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 30, 'Italiana', False),
('Mulher transgênero', 'Preta', 25, 'Brasileira', True),
('Gênero fluido', 'Branca', 26, 'Brasileira', True),
('Outro', 'Indígena', 26, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 23, 'Brasileira', True),
('Homem cisgênero', 'Preta', 30, 'Alemã', True),
('Mulher cisgênero', 'Amarela', 18, 'Argentina', True),
('Mulher cisgênero', 'Outra', 21, 'Brasileira', True),
('Não-binário', 'Branca', 22, 'Brasileira', True),
('Não-binário', 'Branca', 19, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 18, 'Brasileira', False),
('Gênero fluido', 'Branca', 27, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 19, 'Brasileira', True),
('Outro', 'Preta', 21, 'Brasileira', True),
('Homem transgênero', 'Amarela', 29, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 22, 'Brasileira', True),
('Homem cisgênero', 'Preta', 29, 'Brasileira', True),
('Homem cisgênero', 'Branca', 23, 'Brasileira', True),
('Homem transgênero', 'Preta', 29, 'Australiana', True),
('Não-binário', 'Outra', 27, 'Brasileira', False),
('Mulher transgênero', 'Preta', 23, 'Brasileira', True),
('Não-binário', 'Branca', 27, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 17, 'Russa', True),
('Mulher cisgênero', 'Branca', 18, 'Brasileira', False),
('Homem transgênero', 'Amarela', 23, 'Brasileira', True),
('Outro', 'Amarela', 19, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 24, 'Brasileira', True),
('Outro', 'Parda', 28, 'Brasileira', True),
('Gênero fluido', 'Outra', 21, 'Brasileira', False),
('Mulher cisgênero', 'Indígena', 21, 'Brasileira', True),
('Outro', 'Outra', 20, 'Brasileira', True),
('Mulher transgênero', 'Preta', 30, 'Egípcia', True),
('Mulher cisgênero', 'Parda', 19, 'Brasileira', True),
('Homem cisgênero', 'Branca', 21, 'Brasileira', True),
('Outro', 'Amarela', 20, 'Chilena', True),
('Mulher cisgênero', 'Indígena', 22, 'Chilena', True),
('Mulher cisgênero', 'Parda', 17, 'Chinêsa', True),
('Mulher cisgênero', 'Outra', 29, 'Alemã', True),
('Mulher transgênero', 'Preta', 23, 'Canadense', True),
('Homem cisgênero', 'Preta', 27, 'Brasileira', True),
('Gênero fluido', 'Preta', 19, 'Argentina', True),
('Gênero fluido', 'Indígena', 19, 'Sul-africana', True),
('Mulher cisgênero', 'Preta', 22, 'Brasileira', True),
('Mulher transgênero', 'Preta', 22, 'Brasileira', True),
('Não-binário', 'Preta', 25, 'Brasileira', False),
('Outro', 'Indígena', 28, 'Brasileira', True),
('Homem transgênero', 'Outra', 29, 'Brasileira', True),
('Não-binário', 'Amarela', 19, 'Brasileira', True),
('Mulher transgênero', 'Branca', 27, 'Brasileira', True),
('Outro', 'Parda', 20, 'Brasileira', True),
('Mulher transgênero', 'Outra', 29, 'Indiana', True),
('Homem cisgênero', 'Amarela', 28, 'Espanhola', True),
('Não-binário', 'Preta', 24, 'Brasileira', False),
('Mulher transgênero', 'Preta', 24, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 22, 'Brasileira', False),
('Mulher transgênero', 'Branca', 29, 'Brasileira', True),
('Gênero fluido', 'Amarela', 29, 'Alemã', False),
('Não-binário', 'Preta', 22, 'Brasileira', True),
('Homem transgênero', 'Indígena', 29, 'Portuguêsa', True),
('Mulher transgênero', 'Outra', 26, 'Espanhola', True),
('Homem transgênero', 'Indígena', 20, 'Estadunidense', True),
('Mulher cisgênero', 'Parda', 25, 'Portuguêsa', True),
('Gênero fluido', 'Indígena', 20, 'Brasileira', True),
('Gênero fluido', 'Outra', 19, 'Egípcia', False),
('Gênero fluido', 'Parda', 25, 'Italiana', False),
('Não-binário', 'Preta', 28, 'Brasileira', True),
('Homem cisgênero', 'Branca', 26, 'Mexicana', True),
('Homem transgênero', 'Indígena', 24, 'Espanhola', True),
('Homem transgênero', 'Parda', 19, 'Brasileira', True),
('Gênero fluido', 'Outra', 29, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 25, 'Brasileira', True),
('Outro', 'Indígena', 25, 'Canadense', True),
('Gênero fluido', 'Parda', 26, 'Mexicana', True),
('Não-binário', 'Parda', 20, 'Brasileira', True),
('Homem transgênero', 'Preta', 24, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 17, 'Australiana', True),
('Homem transgênero', 'Outra', 25, 'Russa', True),
('Mulher transgênero', 'Amarela', 28, 'Francês', True),
('Homem cisgênero', 'Preta', 26, 'Egípcia', True),
('Mulher transgênero', 'Branca', 28, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 26, 'Sul-africana', False),
('Homem cisgênero', 'Preta', 26, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 26, 'Brasileira', True),
('Mulher cisgênero', 'Preta', 25, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 28, 'Brasileira', True),
('Outro', 'Amarela', 29, 'Brasileira', True),
('Não-binário', 'Amarela', 24, 'Brasileira', True),
('Mulher transgênero', 'Parda', 30, 'Mexicana', True),
('Não-binário', 'Parda', 28, 'Egípcia', True),
('Outro', 'Branca', 25, 'Alemã', True),
('Mulher transgênero', 'Outra', 27, 'Brasileira', False),
('Mulher cisgênero', 'Branca', 24, 'Brasileira', False),
('Outro', 'Preta', 30, 'Italiana', True),
('Mulher transgênero', 'Indígena', 16, 'Canadense', True),
('Outro', 'Outra', 22, 'Chinêsa', True),
('Mulher transgênero', 'Outra', 25, 'Brasileira', True),
('Gênero fluido', 'Branca', 18, 'Brasileira', True),
('Homem cisgênero', 'Parda', 16, 'Brasileira', True),
('Não-binário', 'Preta', 22, 'Alemã', True),
('Mulher cisgênero', 'Preta', 18, 'Brasileira', True),
('Gênero fluido', 'Preta', 25, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 18, 'Brasileira', True),
('Gênero fluido', 'Preta', 22, 'Chinêsa', True),
('Mulher transgênero', 'Outra', 23, 'Brasileira', True),
('Outro', 'Branca', 28, 'Brasileira', True),
('Gênero fluido', 'Outra', 24, 'Chinêsa', True),
('Mulher transgênero', 'Outra', 21, 'Brasileira', True),
('Homem transgênero', 'Amarela', 28, 'Brasileira', True),
('Outro', 'Preta', 30, 'Brasileira', True),
('Homem transgênero', 'Outra', 20, 'Brasileira', True),
('Outro', 'Outra', 19, 'Brasileira', True),
('Mulher transgênero', 'Preta', 17, 'Mexicana', True),
('Mulher cisgênero', 'Preta', 22, 'Brasileira', True),
('Não-binário', 'Preta', 25, 'Brasileira', True),
('Homem cisgênero', 'Parda', 30, 'Brasileira', True),
('Não-binário', 'Indígena', 25, 'Argentina', True),
('Mulher cisgênero', 'Indígena', 29, 'Italiana', True),
('Mulher transgênero', 'Indígena', 16, 'Estadunidense', False),
('Homem transgênero', 'Indígena', 17, 'Russa', True),
('Homem transgênero', 'Parda', 27, 'Brasileira', True),
('Outro', 'Amarela', 30, 'Brasileira', True),
('Homem cisgênero', 'Parda', 26, 'Brasileira', True),
('Mulher transgênero', 'Preta', 29, 'Brasileira', True),
('Gênero fluido', 'Indígena', 20, 'Portuguêsa', True),
('Homem cisgênero', 'Parda', 17, 'Russa', False),
('Gênero fluido', 'Branca', 17, 'Brasileira', False),
('Mulher cisgênero', 'Indígena', 26, 'Sul-africana', True),
('Homem cisgênero', 'Preta', 26, 'Brasileira', True),
('Não-binário', 'Branca', 16, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 29, 'Brasileira', True),
('Outro', 'Amarela', 23, 'Brasileira', True),
('Gênero fluido', 'Preta', 18, 'Brasileira', True),
('Mulher transgênero', 'Preta', 21, 'Brasileira', True),
('Homem transgênero', 'Outra', 30, 'Brasileira', True),
('Não-binário', 'Branca', 28, 'Brasileira', True),
('Gênero fluido', 'Parda', 16, 'Brasileira', True),
('Homem cisgênero', 'Outra', 23, 'Indiana', True),
('Homem transgênero', 'Indígena', 16, 'Chilena', False),
('Mulher transgênero', 'Amarela', 27, 'Egípcia', True),
('Não-binário', 'Preta', 22, 'Brasileira', True),
('Gênero fluido', 'Parda', 23, 'Chinêsa', True),
('Não-binário', 'Preta', 18, 'Brasileira', True),
('Gênero fluido', 'Branca', 26, 'Estadunidense', True),
('Homem transgênero', 'Branca', 18, 'Russa', True),
('Gênero fluido', 'Parda', 23, 'Japonêsa', True),
('Mulher transgênero', 'Preta', 20, 'Brasileira', True),
('Homem transgênero', 'Preta', 18, 'Espanhola', True),
('Gênero fluido', 'Branca', 22, 'Brasileira', True),
('Mulher transgênero', 'Parda', 30, 'Chinêsa', True),
('Não-binário', 'Amarela', 24, 'Brasileira', False),
('Homem transgênero', 'Outra', 21, 'Estadunidense', False),
('Mulher cisgênero', 'Preta', 27, 'Brasileira', True),
('Gênero fluido', 'Preta', 30, 'Brasileira', True),
('Não-binário', 'Parda', 24, 'Brasileira', True),
('Outro', 'Preta', 25, 'Brasileira', True),
('Mulher transgênero', 'Outra', 19, 'Brasileira', True),
('Homem transgênero', 'Indígena', 29, 'Sul-africana', True),
('Mulher cisgênero', 'Branca', 16, 'Canadense', True),
('Outro', 'Branca', 23, 'Indiana', True),
('Homem transgênero', 'Amarela', 26, 'Brasileira', True),
('Homem cisgênero', 'Branca', 20, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 22, 'Brasileira', True),
('Não-binário', 'Parda', 22, 'Portuguêsa', True),
('Homem transgênero', 'Parda', 19, 'Chinêsa', True),
('Outro', 'Indígena', 27, 'Francês', True),
('Mulher cisgênero', 'Branca', 27, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 27, 'Alemã', True),
('Não-binário', 'Indígena', 28, 'Argentina', False),
('Outro', 'Preta', 23, 'Brasileira', True),
('Outro', 'Branca', 21, 'Alemã', False),
('Homem cisgênero', 'Preta', 18, 'Brasileira', True),
('Gênero fluido', 'Preta', 26, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 21, 'Brasileira', True),
('Outro', 'Parda', 23, 'Indiana', True),
('Outro', 'Preta', 29, 'Brasileira', True),
('Outro', 'Parda', 22, 'Portuguêsa', True),
('Mulher cisgênero', 'Amarela', 29, 'Chilena', True),
('Mulher cisgênero', 'Amarela', 25, 'Brasileira', False),
('Homem transgênero', 'Indígena', 22, 'Portuguêsa', True),
('Homem cisgênero', 'Outra', 28, 'Canadense', True),
('Gênero fluido', 'Branca', 25, 'Estadunidense', True),
('Mulher cisgênero', 'Amarela', 18, 'Brasileira', True),
('Mulher transgênero', 'Parda', 24, 'Portuguêsa', True),
('Mulher transgênero', 'Preta', 30, 'Neozelandês', True),
('Gênero fluido', 'Parda', 17, 'Japonêsa', True),
('Não-binário', 'Amarela', 27, 'Brasileira', True),
('Outro', 'Indígena', 27, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 18, 'Brasileira', True),
('Não-binário', 'Parda', 17, 'Argentina', True),
('Mulher cisgênero', 'Indígena', 16, 'Brasileira', False),
('Homem cisgênero', 'Indígena', 26, 'Brasileira', True),
('Homem transgênero', 'Branca', 28, 'Chinêsa', True),
('Mulher transgênero', 'Indígena', 19, 'Brasileira', True),
('Homem transgênero', 'Parda', 23, 'Brasileira', True),
('Gênero fluido', 'Branca', 26, 'Chinêsa', True),
('Mulher cisgênero', 'Branca', 17, 'Brasileira', True),
('Mulher transgênero', 'Outra', 21, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 25, 'Estadunidense', True),
('Não-binário', 'Indígena', 23, 'Japonêsa', True),
('Mulher transgênero', 'Indígena', 20, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 24, 'Japonêsa', True),
('Não-binário', 'Preta', 30, 'Brasileira', True),
('Outro', 'Parda', 16, 'Francês', True),
('Outro', 'Preta', 23, 'Brasileira', True),
('Homem cisgênero', 'Outra', 30, 'Brasileira', True),
('Outro', 'Indígena', 26, 'Brasileira', True),
('Não-binário', 'Indígena', 30, 'Brasileira', True),
('Gênero fluido', 'Branca', 18, 'Brasileira', True),
('Mulher transgênero', 'Parda', 16, 'Brasileira', True),
('Mulher transgênero', 'Branca', 28, 'Espanhola', True),
('Homem transgênero', 'Amarela', 27, 'Brasileira', True),
('Homem cisgênero', 'Parda', 21, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 28, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 25, 'Egípcia', True),
('Mulher cisgênero', 'Parda', 19, 'Chinêsa', True),
('Homem transgênero', 'Outra', 25, 'Brasileira', True),
('Homem cisgênero', 'Preta', 20, 'Chilena', True),
('Mulher transgênero', 'Parda', 20, 'Brasileira', False),
('Mulher cisgênero', 'Indígena', 20, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 18, 'Brasileira', True),
('Gênero fluido', 'Indígena', 19, 'Brasileira', True),
('Homem transgênero', 'Branca', 23, 'Brasileira', True),
('Mulher transgênero', 'Preta', 22, 'Brasileira', False),
('Mulher transgênero', 'Preta', 28, 'Chilena', True),
('Homem cisgênero', 'Indígena', 22, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 29, 'Brasileira', True),
('Gênero fluido', 'Parda', 30, 'Brasileira', True),
('Gênero fluido', 'Amarela', 18, 'Russa', True),
('Homem cisgênero', 'Parda', 28, 'Brasileira', True),
('Outro', 'Indígena', 16, 'Indiana', True),
('Mulher cisgênero', 'Preta', 19, 'Brasileira', False),
('Gênero fluido', 'Amarela', 26, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 16, 'Mexicana', True),
('Mulher transgênero', 'Preta', 28, 'Francês', True),
('Não-binário', 'Indígena', 16, 'Egípcia', True),
('Mulher cisgênero', 'Preta', 29, 'Brasileira', True),
('Não-binário', 'Preta', 26, 'Brasileira', True),
('Homem cisgênero', 'Outra', 17, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 18, 'Nigeriana', True),
('Mulher cisgênero', 'Outra', 20, 'Brasileira', True),
('Gênero fluido', 'Preta', 25, 'Brasileira', True),
('Homem cisgênero', 'Branca', 17, 'Brasileira', True),
('Não-binário', 'Indígena', 22, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 17, 'Brasileira', True),
('Não-binário', 'Indígena', 29, 'Brasileira', True),
('Gênero fluido', 'Amarela', 25, 'Italiana', True),
('Mulher transgênero', 'Branca', 26, 'Brasileira', False),
('Homem cisgênero', 'Branca', 19, 'Sul-africana', True),
('Mulher transgênero', 'Preta', 17, 'Brasileira', True),
('Mulher transgênero', 'Branca', 29, 'Estadunidense', True),
('Outro', 'Indígena', 16, 'Brasileira', True),
('Gênero fluido', 'Branca', 18, 'Brasileira', True),
('Mulher transgênero', 'Outra', 30, 'Chilena', True),
('Outro', 'Amarela', 20, 'Brasileira', True),
('Homem cisgênero', 'Preta', 23, 'Indiana', False),
('Mulher cisgênero', 'Branca', 29, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 20, 'Brasileira', True),
('Homem cisgênero', 'Parda', 21, 'Brasileira', True),
('Homem transgênero', 'Parda', 29, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 18, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 17, 'Brasileira', False),
('Mulher cisgênero', 'Preta', 16, 'Brasileira', True),
('Gênero fluido', 'Preta', 26, 'Canadense', True),
('Outro', 'Preta', 16, 'Espanhola', True),
('Homem transgênero', 'Preta', 25, 'Brasileira', False),
('Gênero fluido', 'Branca', 18, 'Italiana', True),
('Gênero fluido', 'Outra', 30, 'Espanhola', True),
('Homem cisgênero', 'Preta', 30, 'Brasileira', True),
('Homem transgênero', 'Parda', 28, 'Brasileira', False),
('Mulher transgênero', 'Outra', 16, 'Brasileira', True),
('Homem cisgênero', 'Preta', 17, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 20, 'Canadense', True),
('Homem transgênero', 'Branca', 17, 'Brasileira', True),
('Homem transgênero', 'Amarela', 16, 'Nigeriana', True),
('Homem transgênero', 'Branca', 25, 'Brasileira', True),
('Gênero fluido', 'Parda', 30, 'Brasileira', True),
('Outro', 'Outra', 25, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 24, 'Espanhola', True),
('Gênero fluido', 'Indígena', 22, 'Sul-africana', True),
('Gênero fluido', 'Preta', 21, 'Chilena', True),
('Homem cisgênero', 'Amarela', 24, 'Canadense', True),
('Mulher cisgênero', 'Parda', 27, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 23, 'Brasileira', False),
('Não-binário', 'Outra', 21, 'Nigeriana', False),
('Homem transgênero', 'Branca', 22, 'Espanhola', True),
('Outro', 'Preta', 26, 'Brasileira', True),
('Homem cisgênero', 'Branca', 25, 'Brasileira', True),
('Outro', 'Preta', 18, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 25, 'Estadunidense', True),
('Gênero fluido', 'Amarela', 29, 'Brasileira', True),
('Gênero fluido', 'Preta', 22, 'Brasileira', True),
('Não-binário', 'Preta', 29, 'Brasileira', True),
('Não-binário', 'Parda', 28, 'Brasileira', True),
('Homem transgênero', 'Preta', 29, 'Francês', True),
('Não-binário', 'Amarela', 21, 'Indiana', True),
('Mulher transgênero', 'Amarela', 19, 'Egípcia', True),
('Homem transgênero', 'Amarela', 29, 'Brasileira', True),
('Homem cisgênero', 'Preta', 26, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 17, 'Egípcia', True),
('Mulher cisgênero', 'Outra', 26, 'Brasileira', True),
('Homem transgênero', 'Branca', 18, 'Brasileira', True),
('Homem transgênero', 'Indígena', 16, 'Brasileira', True),
('Homem transgênero', 'Preta', 19, 'Brasileira', True),
('Não-binário', 'Outra', 29, 'Japonêsa', False),
('Homem cisgênero', 'Preta', 23, 'Brasileira', True),
('Outro', 'Branca', 22, 'Brasileira', True),
('Homem cisgênero', 'Branca', 26, 'Brasileira', False),
('Mulher transgênero', 'Amarela', 24, 'Espanhola', True),
('Mulher cisgênero', 'Outra', 29, 'Brasileira', True),
('Gênero fluido', 'Parda', 26, 'Canadense', True),
('Gênero fluido', 'Outra', 20, 'Brasileira', False),
('Homem transgênero', 'Branca', 24, 'Francês', True),
('Mulher cisgênero', 'Outra', 23, 'Brasileira', True),
('Mulher transgênero', 'Branca', 28, 'Brasileira', True),
('Outro', 'Parda', 19, 'Brasileira', True),
('Gênero fluido', 'Outra', 16, 'Brasileira', True),
('Outro', 'Amarela', 21, 'Brasileira', True),
('Homem cisgênero', 'Branca', 29, 'Brasileira', True),
('Não-binário', 'Preta', 18, 'Sul-africana', True),
('Gênero fluido', 'Indígena', 17, 'Russa', True),
('Outro', 'Amarela', 24, 'Brasileira', True),
('Outro', 'Parda', 20, 'Brasileira', True),
('Não-binário', 'Amarela', 17, 'Alemã', True),
('Outro', 'Branca', 23, 'Brasileira', True),
('Gênero fluido', 'Branca', 28, 'Brasileira', True),
('Não-binário', 'Preta', 21, 'Brasileira', True),
('Mulher transgênero', 'Amarela', 20, 'Canadense', True),
('Gênero fluido', 'Outra', 24, 'Brasileira', True),
('Outro', 'Amarela', 28, 'Australiana', True),
('Homem transgênero', 'Amarela', 20, 'Francês', True),
('Outro', 'Preta', 27, 'Estadunidense', True),
('Gênero fluido', 'Outra', 23, 'Alemã', False),
('Gênero fluido', 'Parda', 21, 'Brasileira', True),
('Não-binário', 'Amarela', 22, 'Brasileira', True),
('Não-binário', 'Parda', 23, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 28, 'Brasileira', True),
('Outro', 'Parda', 19, 'Brasileira', True),
('Homem transgênero', 'Preta', 29, 'Brasileira', True),
('Mulher transgênero', 'Branca', 26, 'Brasileira', True),
('Mulher transgênero', 'Preta', 30, 'Brasileira', True),
('Não-binário', 'Preta', 28, 'Brasileira', True),
('Não-binário', 'Parda', 19, 'Mexicana', True),
('Homem cisgênero', 'Outra', 26, 'Brasileira', True),
('Homem transgênero', 'Preta', 24, 'Brasileira', True),
('Homem cisgênero', 'Outra', 28, 'Alemã', True),
('Homem transgênero', 'Preta', 16, 'Brasileira', True),
('Não-binário', 'Indígena', 22, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 23, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 28, 'Espanhola', True),
('Homem transgênero', 'Parda', 24, 'Argentina', True),
('Mulher transgênero', 'Parda', 27, 'Brasileira', True),
('Mulher transgênero', 'Parda', 28, 'Francês', True),
('Gênero fluido', 'Parda', 23, 'Sul-africana', True),
('Homem cisgênero', 'Branca', 18, 'Brasileira', False),
('Mulher cisgênero', 'Amarela', 29, 'Brasileira', True),
('Outro', 'Indígena', 20, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 25, 'Brasileira', True),
('Homem cisgênero', 'Preta', 17, 'Brasileira', True),
('Gênero fluido', 'Parda', 27, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 23, 'Brasileira', False),
('Outro', 'Amarela', 19, 'Mexicana', False),
('Não-binário', 'Indígena', 26, 'Brasileira', True),
('Mulher transgênero', 'Branca', 19, 'Francês', True),
('Mulher cisgênero', 'Amarela', 26, 'Brasileira', True),
('Não-binário', 'Indígena', 21, 'Chinêsa', True),
('Homem cisgênero', 'Indígena', 22, 'Brasileira', True),
('Homem cisgênero', 'Preta', 29, 'Brasileira', True),
('Homem cisgênero', 'Outra', 18, 'Brasileira', True),
('Outro', 'Parda', 21, 'Brasileira', False),
('Mulher transgênero', 'Preta', 29, 'Nigeriana', True),
('Homem transgênero', 'Preta', 21, 'Mexicana', True),
('Homem transgênero', 'Preta', 20, 'Brasileira', True),
('Homem cisgênero', 'Branca', 22, 'Brasileira', True),
('Não-binário', 'Outra', 24, 'Brasileira', True),
('Gênero fluido', 'Parda', 24, 'Brasileira', True),
('Gênero fluido', 'Branca', 26, 'Brasileira', True),
('Homem transgênero', 'Branca', 26, 'Brasileira', True),
('Homem transgênero', 'Branca', 18, 'Italiana', True),
('Gênero fluido', 'Preta', 17, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 26, 'Brasileira', True),
('Outro', 'Indígena', 23, 'Australiana', True),
('Outro', 'Amarela', 23, 'Brasileira', True),
('Mulher transgênero', 'Outra', 20, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 22, 'Italiana', True),
('Outro', 'Preta', 27, 'Francês', True),
('Outro', 'Outra', 19, 'Brasileira', True),
('Não-binário', 'Amarela', 24, 'Mexicana', True),
('Homem transgênero', 'Preta', 20, 'Brasileira', True),
('Não-binário', 'Parda', 29, 'Brasileira', True),
('Homem transgênero', 'Parda', 30, 'Brasileira', True),
('Mulher transgênero', 'Preta', 26, 'Brasileira', True),
('Homem cisgênero', 'Branca', 24, 'Brasileira', True),
('Homem transgênero', 'Indígena', 30, 'Alemã', True),
('Não-binário', 'Branca', 17, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 19, 'Alemã', True),
('Não-binário', 'Preta', 20, 'Brasileira', True),
('Homem cisgênero', 'Outra', 24, 'Brasileira', True),
('Não-binário', 'Preta', 20, 'Brasileira', True),
('Outro', 'Amarela', 24, 'Nigeriana', True),
('Mulher cisgênero', 'Parda', 29, 'Brasileira', True),
('Não-binário', 'Branca', 25, 'Brasileira', True),
('Gênero fluido', 'Indígena', 21, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 28, 'Brasileira', False),
('Mulher cisgênero', 'Amarela', 25, 'Brasileira', True),
('Outro', 'Amarela', 24, 'Chinêsa', True),
('Mulher transgênero', 'Indígena', 19, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 18, 'Mexicana', False),
('Gênero fluido', 'Amarela', 18, 'Brasileira', True),
('Gênero fluido', 'Parda', 16, 'Estadunidense', True),
('Homem cisgênero', 'Parda', 23, 'Japonêsa', True),
('Não-binário', 'Preta', 24, 'Brasileira', True),
('Outro', 'Outra', 17, 'Brasileira', True),
('Homem transgênero', 'Outra', 27, 'Portuguêsa', False),
('Homem cisgênero', 'Parda', 28, 'Egípcia', True),
('Homem cisgênero', 'Parda', 22, 'Brasileira', True),
('Outro', 'Branca', 30, 'Brasileira', True),
('Não-binário', 'Amarela', 18, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 18, 'Indiana', True),
('Mulher cisgênero', 'Branca', 23, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 23, 'Russa', True),
('Mulher cisgênero', 'Preta', 18, 'Brasileira', True),
('Não-binário', 'Outra', 21, 'Chilena', True),
('Não-binário', 'Amarela', 30, 'Brasileira', True),
('Homem transgênero', 'Outra', 30, 'Sul-africana', True),
('Outro', 'Indígena', 17, 'Nigeriana', True),
('Gênero fluido', 'Preta', 24, 'Brasileira', True),
('Homem cisgênero', 'Branca', 28, 'Brasileira', True),
('Gênero fluido', 'Indígena', 30, 'Sul-africana', True),
('Outro', 'Preta', 25, 'Brasileira', True),
('Gênero fluido', 'Preta', 20, 'Brasileira', False),
('Homem transgênero', 'Parda', 18, 'Brasileira', True),
('Homem transgênero', 'Branca', 29, 'Espanhola', True),
('Outro', 'Indígena', 16, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 30, 'Brasileira', True),
('Homem transgênero', 'Branca', 29, 'Brasileira', False),
('Homem cisgênero', 'Branca', 23, 'Brasileira', True),
('Homem transgênero', 'Parda', 16, 'Australiana', True),
('Gênero fluido', 'Branca', 29, 'Chilena', True),
('Mulher cisgênero', 'Branca', 26, 'Argentina', False),
('Mulher transgênero', 'Indígena', 28, 'Estadunidense', True),
('Não-binário', 'Parda', 24, 'Brasileira', False),
('Gênero fluido', 'Preta', 27, 'Brasileira', True),
('Outro', 'Preta', 16, 'Egípcia', True),
('Não-binário', 'Parda', 21, 'Brasileira', True),
('Gênero fluido', 'Indígena', 25, 'Neozelandês', True),
('Mulher cisgênero', 'Indígena', 25, 'Italiana', True),
('Mulher cisgênero', 'Outra', 30, 'Portuguêsa', True),
('Homem transgênero', 'Indígena', 25, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 19, 'Brasileira', True),
('Mulher transgênero', 'Branca', 28, 'Portuguêsa', True),
('Homem transgênero', 'Amarela', 24, 'Brasileira', True),
('Mulher transgênero', 'Branca', 20, 'Brasileira', True),
('Outro', 'Branca', 27, 'Brasileira', True),
('Gênero fluido', 'Preta', 29, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 22, 'Brasileira', True),
('Mulher transgênero', 'Parda', 28, 'Brasileira', True),
('Mulher transgênero', 'Amarela', 20, 'Mexicana', True),
('Não-binário', 'Preta', 24, 'Brasileira', True),
('Gênero fluido', 'Outra', 17, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 18, 'Brasileira', True),
('Não-binário', 'Amarela', 18, 'Egípcia', True),
('Mulher cisgênero', 'Amarela', 23, 'Canadense', True),
('Homem cisgênero', 'Indígena', 28, 'Brasileira', True),
('Mulher transgênero', 'Parda', 26, 'Portuguêsa', True),
('Outro', 'Parda', 16, 'Brasileira', True),
('Mulher transgênero', 'Branca', 18, 'Mexicana', True),
('Outro', 'Indígena', 27, 'Brasileira', True),
('Gênero fluido', 'Parda', 18, 'Brasileira', True),
('Homem cisgênero', 'Outra', 28, 'Brasileira', True),
('Não-binário', 'Outra', 20, 'Brasileira', True),
('Não-binário', 'Indígena', 19, 'Australiana', True),
('Gênero fluido', 'Preta', 23, 'Brasileira', True),
('Outro', 'Parda', 21, 'Sul-africana', True),
('Não-binário', 'Outra', 22, 'Brasileira', True),
('Não-binário', 'Preta', 16, 'Egípcia', True),
('Homem transgênero', 'Outra', 25, 'Nigeriana', True),
('Mulher cisgênero', 'Amarela', 17, 'Brasileira', True),
('Mulher transgênero', 'Branca', 28, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 22, 'Indiana', True),
('Outro', 'Parda', 23, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 17, 'Alemã', True),
('Gênero fluido', 'Indígena', 29, 'Sul-africana', True),
('Não-binário', 'Parda', 17, 'Brasileira', True),
('Mulher transgênero', 'Branca', 19, 'Brasileira', True),
('Gênero fluido', 'Branca', 24, 'Brasileira', True),
('Mulher transgênero', 'Branca', 19, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 28, 'Brasileira', True),
('Não-binário', 'Parda', 28, 'Brasileira', True),
('Gênero fluido', 'Parda', 23, 'Alemã', True),
('Mulher cisgênero', 'Branca', 30, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 20, 'Canadense', False),
('Homem transgênero', 'Indígena', 21, 'Chinêsa', True),
('Homem transgênero', 'Indígena', 29, 'Brasileira', True),
('Homem transgênero', 'Outra', 30, 'Brasileira', True),
('Mulher transgênero', 'Parda', 29, 'Brasileira', True),
('Homem cisgênero', 'Branca', 30, 'Brasileira', True),
('Gênero fluido', 'Parda', 16, 'Estadunidense', True),
('Outro', 'Amarela', 16, 'Australiana', True),
('Mulher cisgênero', 'Outra', 18, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 27, 'Brasileira', True),
('Mulher transgênero', 'Preta', 21, 'Brasileira', True),
('Mulher transgênero', 'Outra', 17, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 20, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 24, 'Alemã', False),
('Homem transgênero', 'Outra', 27, 'Francês', True),
('Não-binário', 'Parda', 16, 'Indiana', True),
('Homem cisgênero', 'Outra', 29, 'Brasileira', True),
('Homem cisgênero', 'Parda', 23, 'Brasileira', True),
('Não-binário', 'Parda', 17, 'Sul-africana', True),
('Mulher cisgênero', 'Preta', 29, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 19, 'Egípcia', True),
('Homem cisgênero', 'Outra', 22, 'Argentina', True),
('Homem cisgênero', 'Parda', 24, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 30, 'Brasileira', True),
('Não-binário', 'Outra', 19, 'Indiana', True),
('Gênero fluido', 'Preta', 19, 'Brasileira', True),
('Gênero fluido', 'Amarela', 30, 'Brasileira', True),
('Homem transgênero', 'Parda', 22, 'Brasileira', True),
('Gênero fluido', 'Outra', 20, 'Brasileira', True),
('Outro', 'Preta', 16, 'Brasileira', False),
('Homem transgênero', 'Outra', 19, 'Brasileira', False),
('Homem cisgênero', 'Amarela', 17, 'Egípcia', True),
('Não-binário', 'Branca', 21, 'Brasileira', True),
('Mulher transgênero', 'Preta', 23, 'Brasileira', True),
('Outro', 'Outra', 22, 'Neozelandês', True),
('Não-binário', 'Indígena', 27, 'Brasileira', True),
('Não-binário', 'Branca', 25, 'Sul-africana', True),
('Mulher transgênero', 'Preta', 29, 'Alemã', True),
('Gênero fluido', 'Branca', 28, 'Brasileira', True),
('Não-binário', 'Indígena', 21, 'Canadense', True),
('Gênero fluido', 'Parda', 25, 'Brasileira', True),
('Homem transgênero', 'Indígena', 26, 'Brasileira', True),
('Não-binário', 'Indígena', 17, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 18, 'Brasileira', True),
('Não-binário', 'Outra', 19, 'Brasileira', True),
('Homem transgênero', 'Parda', 20, 'Brasileira', False),
('Homem cisgênero', 'Amarela', 24, 'Brasileira', True),
('Homem transgênero', 'Indígena', 25, 'Brasileira', True),
('Outro', 'Outra', 25, 'Nigeriana', False),
('Mulher cisgênero', 'Indígena', 26, 'Brasileira', False),
('Gênero fluido', 'Branca', 30, 'Japonêsa', False),
('Gênero fluido', 'Branca', 28, 'Mexicana', True),
('Outro', 'Amarela', 26, 'Estadunidense', True),
('Mulher transgênero', 'Indígena', 17, 'Indiana', True),
('Outro', 'Amarela', 19, 'Brasileira', True),
('Outro', 'Indígena', 24, 'Brasileira', True),
('Gênero fluido', 'Outra', 17, 'Brasileira', True),
('Gênero fluido', 'Parda', 16, 'Chilena', True),
('Homem cisgênero', 'Outra', 23, 'Brasileira', False),
('Não-binário', 'Parda', 18, 'Brasileira', True),
('Homem transgênero', 'Parda', 19, 'Argentina', True),
('Mulher cisgênero', 'Amarela', 16, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 17, 'Brasileira', False),
('Homem cisgênero', 'Parda', 23, 'Brasileira', True),
('Homem transgênero', 'Preta', 23, 'Brasileira', True),
('Não-binário', 'Preta', 25, 'Brasileira', True),
('Mulher transgênero', 'Amarela', 28, 'Brasileira', True),
('Não-binário', 'Indígena', 25, 'Brasileira', True),
('Gênero fluido', 'Indígena', 16, 'Indiana', True),
('Gênero fluido', 'Preta', 27, 'Brasileira', False),
('Mulher cisgênero', 'Outra', 22, 'Brasileira', True),
('Gênero fluido', 'Preta', 24, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 25, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 16, 'Estadunidense', True),
('Não-binário', 'Amarela', 22, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 26, 'Brasileira', True),
('Gênero fluido', 'Branca', 30, 'Brasileira', True),
('Não-binário', 'Outra', 22, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 18, 'Mexicana', True),
('Homem cisgênero', 'Preta', 21, 'Japonêsa', True),
('Outro', 'Indígena', 20, 'Russa', True),
('Mulher transgênero', 'Branca', 16, 'Brasileira', True),
('Homem cisgênero', 'Parda', 25, 'Brasileira', True),
('Outro', 'Indígena', 22, 'Brasileira', True),
('Homem transgênero', 'Indígena', 23, 'Brasileira', True),
('Mulher transgênero', 'Preta', 28, 'Brasileira', False),
('Não-binário', 'Amarela', 25, 'Indiana', True),
('Não-binário', 'Branca', 18, 'Brasileira', True),
('Homem transgênero', 'Amarela', 25, 'Brasileira', True),
('Homem transgênero', 'Indígena', 23, 'Russa', True),
('Mulher transgênero', 'Indígena', 27, 'Brasileira', True),
('Mulher transgênero', 'Amarela', 21, 'Brasileira', True),
('Homem transgênero', 'Amarela', 24, 'Japonêsa', True),
('Homem transgênero', 'Preta', 30, 'Australiana', True),
('Homem cisgênero', 'Indígena', 20, 'Brasileira', True),
('Homem transgênero', 'Indígena', 28, 'Russa', True),
('Mulher transgênero', 'Outra', 23, 'Brasileira', True),
('Não-binário', 'Indígena', 29, 'Russa', True),
('Homem transgênero', 'Branca', 22, 'Chilena', True),
('Mulher transgênero', 'Indígena', 22, 'Brasileira', True),
('Mulher cisgênero', 'Preta', 18, 'Egípcia', True),
('Não-binário', 'Parda', 29, 'Brasileira', True),
('Mulher cisgênero', 'Branca', 19, 'Francês', True),
('Homem cisgênero', 'Amarela', 19, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 17, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 20, 'Espanhola', True),
('Mulher cisgênero', 'Outra', 19, 'Brasileira', False),
('Homem transgênero', 'Parda', 22, 'Brasileira', True),
('Homem cisgênero', 'Outra', 23, 'Italiana', True),
('Homem transgênero', 'Amarela', 18, 'Brasileira', True),
('Homem transgênero', 'Branca', 16, 'Russa', True),
('Gênero fluido', 'Amarela', 17, 'Canadense', True),
('Homem transgênero', 'Amarela', 20, 'Brasileira', False),
('Outro', 'Indígena', 19, 'Brasileira', True),
('Homem cisgênero', 'Outra', 19, 'Sul-africana', True),
('Mulher cisgênero', 'Preta', 17, 'Alemã', True),
('Homem transgênero', 'Amarela', 28, 'Neozelandês', True),
('Outro', 'Preta', 23, 'Neozelandês', True),
('Homem cisgênero', 'Preta', 29, 'Portuguêsa', True),
('Homem transgênero', 'Indígena', 23, 'Argentina', True),
('Outro', 'Outra', 20, 'Brasileira', True),
('Gênero fluido', 'Indígena', 22, 'Brasileira', True),
('Gênero fluido', 'Parda', 19, 'Brasileira', False),
('Mulher transgênero', 'Parda', 28, 'Indiana', True),
('Homem cisgênero', 'Branca', 20, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 29, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 30, 'Japonêsa', True),
('Não-binário', 'Amarela', 26, 'Chinêsa', True),
('Homem cisgênero', 'Outra', 22, 'Brasileira', True),
('Homem cisgênero', 'Branca', 27, 'Sul-africana', True),
('Homem cisgênero', 'Indígena', 27, 'Argentina', True),
('Outro', 'Preta', 17, 'Argentina', True),
('Gênero fluido', 'Amarela', 23, 'Brasileira', True),
('Homem cisgênero', 'Branca', 26, 'Brasileira', True),
('Não-binário', 'Parda', 30, 'Brasileira', True),
('Gênero fluido', 'Branca', 27, 'Brasileira', True),
('Outro', 'Branca', 25, 'Brasileira', True),
('Gênero fluido', 'Parda', 29, 'Brasileira', False),
('Mulher cisgênero', 'Outra', 19, 'Brasileira', True),
('Mulher transgênero', 'Preta', 29, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 16, 'Brasileira', True),
('Gênero fluido', 'Amarela', 19, 'Brasileira', True),
('Mulher cisgênero', 'Preta', 17, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 25, 'Russa', False),
('Não-binário', 'Amarela', 30, 'Brasileira', True),
('Gênero fluido', 'Amarela', 23, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 22, 'Brasileira', True),
('Mulher cisgênero', 'Outra', 28, 'Egípcia', True),
('Gênero fluido', 'Parda', 27, 'Brasileira', True),
('Homem cisgênero', 'Preta', 25, 'Brasileira', True),
('Mulher transgênero', 'Amarela', 24, 'Brasileira', True),
('Homem cisgênero', 'Preta', 25, 'Francês', True),
('Não-binário', 'Outra', 24, 'Brasileira', True),
('Homem cisgênero', 'Outra', 28, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 19, 'Brasileira', True),
('Gênero fluido', 'Parda', 18, 'Brasileira', True),
('Gênero fluido', 'Outra', 29, 'Brasileira', True),
('Gênero fluido', 'Outra', 19, 'Brasileira', True),
('Gênero fluido', 'Preta', 16, 'Brasileira', True),
('Não-binário', 'Preta', 25, 'Brasileira', True),
('Mulher transgênero', 'Preta', 17, 'Brasileira', True),
('Gênero fluido', 'Outra', 21, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 18, 'Brasileira', True),
('Não-binário', 'Branca', 25, 'Brasileira', True),
('Homem transgênero', 'Outra', 29, 'Argentina', True),
('Mulher transgênero', 'Parda', 23, 'Italiana', True),
('Homem cisgênero', 'Preta', 24, 'Brasileira', True),
('Outro', 'Indígena', 30, 'Francês', True),
('Homem cisgênero', 'Amarela', 18, 'Brasileira', False),
('Homem cisgênero', 'Preta', 21, 'Brasileira', True),
('Não-binário', 'Parda', 25, 'Francês', True),
('Mulher cisgênero', 'Preta', 18, 'Brasileira', True),
('Homem transgênero', 'Amarela', 18, 'Brasileira', True),
('Outro', 'Parda', 29, 'Chinêsa', True),
('Gênero fluido', 'Preta', 30, 'Brasileira', True),
('Gênero fluido', 'Branca', 24, 'Brasileira', True),
('Mulher transgênero', 'Indígena', 21, 'Brasileira', True),
('Gênero fluido', 'Indígena', 17, 'Brasileira', True),
('Gênero fluido', 'Indígena', 17, 'Brasileira', True),
('Mulher cisgênero', 'Indígena', 27, 'Brasileira', True),
('Gênero fluido', 'Branca', 24, 'Indiana', True),
('Mulher transgênero', 'Outra', 22, 'Brasileira', True),
('Mulher transgênero', 'Preta', 21, 'Alemã', True),
('Outro', 'Branca', 22, 'Egípcia', True),
('Gênero fluido', 'Parda', 27, 'Brasileira', True),
('Mulher transgênero', 'Preta', 23, 'Brasileira', True),
('Não-binário', 'Amarela', 28, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 27, 'Nigeriana', True),
('Mulher cisgênero', 'Preta', 18, 'Brasileira', True),
('Gênero fluido', 'Preta', 29, 'Canadense', False),
('Não-binário', 'Preta', 21, 'Brasileira', True),
('Gênero fluido', 'Indígena', 25, 'Brasileira', True),
('Outro', 'Preta', 18, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 20, 'Brasileira', True),
('Homem cisgênero', 'Branca', 28, 'Francês', True),
('Homem cisgênero', 'Outra', 25, 'Italiana', True),
('Outro', 'Branca', 18, 'Brasileira', True),
('Outro', 'Parda', 17, 'Francês', True),
('Não-binário', 'Preta', 16, 'Canadense', True),
('Outro', 'Preta', 24, 'Brasileira', True),
('Mulher cisgênero', 'Preta', 25, 'Brasileira', True),
('Homem transgênero', 'Amarela', 17, 'Italiana', True),
('Mulher transgênero', 'Indígena', 24, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 24, 'Sul-africana', True),
('Gênero fluido', 'Preta', 22, 'Brasileira', True),
('Outro', 'Outra', 20, 'Brasileira', True),
('Gênero fluido', 'Branca', 24, 'Brasileira', True),
('Outro', 'Branca', 21, 'Chilena', True),
('Mulher transgênero', 'Branca', 30, 'Japonêsa', True),
('Gênero fluido', 'Indígena', 21, 'Indiana', True),
('Gênero fluido', 'Parda', 21, 'Estadunidense', True),
('Gênero fluido', 'Amarela', 18, 'Estadunidense', True),
('Gênero fluido', 'Parda', 26, 'Brasileira', True),
('Outro', 'Parda', 24, 'Brasileira', True),
('Homem transgênero', 'Indígena', 19, 'Chilena', True),
('Homem cisgênero', 'Indígena', 20, 'Neozelandês', True),
('Homem cisgênero', 'Preta', 24, 'Alemã', True),
('Não-binário', 'Indígena', 16, 'Brasileira', True),
('Não-binário', 'Branca', 28, 'Mexicana', True),
('Outro', 'Amarela', 20, 'Brasileira', True),
('Outro', 'Branca', 24, 'Brasileira', True),
('Mulher cisgênero', 'Amarela', 26, 'Brasileira', True),
('Gênero fluido', 'Indígena', 26, 'Francês', True),
('Outro', 'Preta', 21, 'Indiana', True),
('Mulher transgênero', 'Outra', 17, 'Brasileira', True),
('Não-binário', 'Indígena', 17, 'Brasileira', False),
('Mulher transgênero', 'Outra', 29, 'Brasileira', True),
('Homem transgênero', 'Indígena', 18, 'Chinêsa', True),
('Não-binário', 'Branca', 29, 'Brasileira', True),
('Homem transgênero', 'Outra', 19, 'Brasileira', True),
('Outro', 'Preta', 29, 'Brasileira', True),
('Gênero fluido', 'Preta', 24, 'Alemã', True),
('Gênero fluido', 'Outra', 26, 'Brasileira', True),
('Mulher transgênero', 'Preta', 18, 'Brasileira', True),
('Homem cisgênero', 'Indígena', 26, 'Egípcia', True),
('Mulher transgênero', 'Outra', 20, 'Brasileira', True),
('Gênero fluido', 'Branca', 27, 'Brasileira', True),
('Mulher cisgênero', 'Parda', 21, 'Brasileira', True),
('Mulher transgênero', 'Parda', 28, 'Argentina', True),
('Mulher cisgênero', 'Branca', 21, 'Brasileira', True),
('Gênero fluido', 'Indígena', 19, 'Brasileira', True),
('Mulher transgênero', 'Parda', 19, 'Australiana', True),
('Mulher transgênero', 'Outra', 28, 'Brasileira', True),
('Homem cisgênero', 'Amarela', 16, 'Sul-africana', True),
('Outro', 'Outra', 20, 'Brasileira', True),
('Outro', 'Preta', 26, 'Brasileira', True),
('Mulher transgênero', 'Preta', 22, 'Brasileira', True),
('Outro', 'Branca', 17, 'Brasileira', True),
('Homem transgênero', 'Indígena', 27, 'Brasileira', True),
('Homem transgênero', 'Indígena', 19, 'Australiana', True),
('Não-binário', 'Indígena', 25, 'Francês', True),
('Mulher transgênero', 'Preta', 27, 'Brasileira', True),
('Gênero fluido', 'Indígena', 16, 'Sul-africana', True),
('Homem transgênero', 'Amarela', 30, 'Brasileira', True);
