INSERT INTO docentes (genero, raca_cor, idade, nacionalidade, formacao, regime_trabalho) VALUES
('Feminino', 'Branca', 40, 'Brasileira', 'Doutorado em Medicina', 'dedicação exclusiva'),
('Masculino', 'Pardo', 35, 'Brasileira', 'Mestrado em Pedagogia', 'tempo integral'),
('Masculino', 'Negro', 50, 'Brasileira', 'Doutorado em Engenharia Civil', 'tempo parcial'),
('Homem cisgênero', 'Branca', 30, 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', 26, 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 34, 'Estadunidense', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', 59, 'Japonêsa', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 44, 'Nigeriana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 33, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', 36, 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', 31, 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', 46, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', 57, 'Chinêsa', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Outra', 55, 'Canadense', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 56, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 46, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 37, 'Neozelandês', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 52, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 58, 'Neozelandês', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', 33, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 36, 'Neozelandês', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 51, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 51, 'Estadunidense', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 56, 'Chinêsa', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 25, 'Francês', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 51, 'Estadunidense', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 26, 'Italiana', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 43, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Preta', 41, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Outra', 48, 'Russa', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 54, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', 41, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Preta', 59, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', 47, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 42, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 27, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 57, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Outra', 44, 'Egípcia', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Outra', 49, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 49, 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', 26, 'Chinêsa', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Branca', 54, 'Chilena', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 38, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 29, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Preta', 52, 'Estadunidense', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', 43, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 37, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Amarela', 46, 'Indiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 33, 'Alemã', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', 38, 'Nigeriana', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', 41, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', 35, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', 59, 'Espanhola', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Amarela', 54, 'Espanhola', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 43, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Outra', 51, 'Chinêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', 50, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 54, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Outra', 54, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 55, 'Nigeriana', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 26, 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 40, 'Alemã', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 55, 'Australiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', 33, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', 25, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 52, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Outra', 28, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 40, 'Nigeriana', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', 28, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 56, 'Canadense', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', 34, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 59, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', 50, 'Argentina', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Preta', 53, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', 31, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 26, 'Alemã', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 28, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', 50, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 44, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', 43, 'Alemã', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 53, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 26, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 46, 'Portuguêsa', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 43, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 41, 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 32, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 32, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', 41, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', 29, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 44, 'Egípcia', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 39, 'Argentina', 'Mestrado', 'Tempo Integral'),
('Outro', 'Outra', 26, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Preta', 59, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', 38, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 47, 'Australiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', 30, 'Neozelandês', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 52, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', 55, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', 46, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 39, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', 33, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 49, 'Mexicana', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', 41, 'Egípcia', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 33, 'Japonêsa', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Amarela', 28, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 60, 'Espanhola', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 60, 'Alemã', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 44, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 55, 'Portuguêsa', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', 47, 'Russa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 40, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Outra', 50, 'Australiana', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 35, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 37, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', 37, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', 49, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 37, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Indígena', 29, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 36, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Outra', 25, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 30, 'Francês', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 53, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 43, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', 33, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 42, 'Espanhola', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', 44, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 58, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 56, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', 45, 'Argentina', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 39, 'Argentina', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', 34, 'Alemã', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 50, 'Nigeriana', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 57, 'Argentina', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 33, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 32, 'Estadunidense', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Branca', 38, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Preta', 51, 'Russa', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', 52, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Branca', 43, 'Nigeriana', 'Mestrado', 'Tempo Integral'),
('Outro', 'Amarela', 60, 'Mexicana', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', 50, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 44, 'Espanhola', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 33, 'Egípcia', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 26, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 52, 'Egípcia', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', 31, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 31, 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', 26, 'Neozelandês', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 58, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 47, 'Neozelandês', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 52, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Amarela', 56, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 37, 'Chilena', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Outra', 50, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', 33, 'Sul-africana', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', 60, 'Estadunidense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 47, 'Egípcia', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 43, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', 44, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 42, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', 38, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', 32, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Outra', 47, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 52, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 32, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 58, 'Francês', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 40, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 44, 'Portuguêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', 59, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Branca', 47, 'Mexicana', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', 51, 'Argentina', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', 46, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', 59, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 51, 'Estadunidense', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Outra', 33, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', 42, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 52, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', 53, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 42, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 45, 'Estadunidense', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 28, 'Neozelandês', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 28, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 29, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 46, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 55, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 60, 'Chinêsa', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', 28, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', 25, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', 50, 'Chinêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 54, 'Alemã', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 52, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 60, 'Russa', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Branca', 39, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 48, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 54, 'Espanhola', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 50, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 26, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', 56, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', 45, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 27, 'Chinêsa', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', 42, 'Nigeriana', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 32, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 27, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 25, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', 58, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', 35, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', 42, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Parda', 40, 'Indiana', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 59, 'Francês', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Branca', 55, 'Egípcia', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 40, 'Sul-africana', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 41, 'Neozelandês', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 25, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', 29, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', 57, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 44, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 31, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', 27, 'Australiana', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 41, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', 27, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 43, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 60, 'Neozelandês', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', 28, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 59, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Outra', 60, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 54, 'Portuguêsa', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', 50, 'Francês', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 29, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 48, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 28, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', 48, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 35, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 43, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Outra', 44, 'Nigeriana', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 30, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', 26, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 33, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', 29, 'Chinêsa', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Outra', 40, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 42, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', 60, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', 31, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', 57, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Outra', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 50, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Outra', 30, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 35, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 32, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', 58, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 33, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', 47, 'Russa', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 48, 'Sul-africana', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Outra', 26, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', 38, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 27, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Preta', 49, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Amarela', 36, 'Egípcia', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 58, 'Chinêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 32, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 47, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 55, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 54, 'Japonêsa', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 44, 'Italiana', 'Doutorado', 'Tempo Integral'),
('Outro', 'Preta', 53, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 34, 'Mexicana', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 45, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 27, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 45, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 60, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', 30, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', 41, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 46, 'Nigeriana', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 36, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 60, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', 56, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Branca', 41, 'Italiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 59, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 27, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 30, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 32, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Outra', 51, 'Neozelandês', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 48, 'Italiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 27, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 45, 'Australiana', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 45, 'Chilena', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Amarela', 50, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', 26, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', 44, 'Japonêsa', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', 44, 'Espanhola', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 60, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 59, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 38, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 49, 'Sul-africana', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 30, 'Nigeriana', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 39, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Indígena', 58, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 45, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 38, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', 29, 'Alemã', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', 43, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', 57, 'Mexicana', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 46, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 45, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 25, 'Italiana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 35, 'Australiana', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', 41, 'Estadunidense', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 31, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 52, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 51, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Outra', 30, 'Portuguêsa', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', 36, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', 48, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', 56, 'Chilena', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 51, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', 53, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', 42, 'Argentina', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', 57, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 35, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 35, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 26, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 25, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 32, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 40, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Preta', 34, 'Estadunidense', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 38, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 59, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 35, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', 54, 'Chilena', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 59, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', 45, 'Mexicana', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', 30, 'Argentina', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', 59, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', 39, 'Australiana', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', 37, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', 38, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', 29, 'Nigeriana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 49, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 37, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 44, 'Indiana', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Outra', 50, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 36, 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Outra', 45, 'Russa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 41, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Outra', 55, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Indígena', 38, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 56, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 29, 'Nigeriana', 'Doutorado', 'Tempo Integral'),
('Outro', 'Branca', 50, 'Estadunidense', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', 45, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 36, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 33, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', 32, 'Estadunidense', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 46, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', 41, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', 34, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 25, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 53, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', 45, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', 43, 'Portuguêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 40, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', 55, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Outra', 30, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 40, 'Estadunidense', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 41, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 29, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 54, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 58, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 25, 'Russa', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 33, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 49, 'Francês', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', 48, 'Mexicana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 57, 'Egípcia', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 45, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Branca', 38, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 55, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', 54, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Branca', 58, 'Australiana', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Branca', 50, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 37, 'Francês', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 58, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 39, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 47, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 33, 'Argentina', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Outra', 53, 'Nigeriana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 34, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Branca', 44, 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 56, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Preta', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 37, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 36, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 38, 'Australiana', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Branca', 27, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', 40, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 40, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', 39, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 29, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 41, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', 56, 'Francês', 'Mestrado', 'Tempo Integral'),
('Outro', 'Preta', 57, 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', 34, 'Sul-africana', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 58, 'Portuguêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 49, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', 57, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 38, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 39, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 42, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 28, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', 59, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 54, 'Nigeriana', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', 43, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 40, 'Sul-africana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 57, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', 60, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Preta', 36, 'Chilena', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 51, 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 31, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 26, 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', 42, 'Nigeriana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 29, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 58, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 46, 'Chilena', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', 26, 'Nigeriana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 25, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 37, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 50, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Indígena', 25, 'Francês', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 38, 'Nigeriana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 49, 'Canadense', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 33, 'Chilena', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', 41, 'Argentina', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Outra', 58, 'Australiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 44, 'Nigeriana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 58, 'Estadunidense', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 31, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Preta', 41, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 52, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 49, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Preta', 52, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 52, 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Outro', 'Outra', 44, 'Japonêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 53, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 50, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 53, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 32, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Branca', 35, 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 33, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', 58, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 47, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 27, 'Indiana', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Branca', 59, 'Chilena', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', 51, 'Chinêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 30, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 28, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 31, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Preta', 54, 'Argentina', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 55, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 49, 'Nigeriana', 'Mestrado', 'Tempo Integral'),
('Outro', 'Indígena', 54, 'Sul-africana', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', 37, 'Mexicana', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', 57, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 39, 'Russa', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Amarela', 26, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', 54, 'Chilena', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 58, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', 46, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 52, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 56, 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 58, 'Chilena', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 60, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 54, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 57, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 44, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 45, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 29, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 47, 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 31, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', 47, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 34, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', 50, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 25, 'Indiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 45, 'Australiana', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', 59, 'Russa', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Branca', 58, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 46, 'Mexicana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 44, 'Egípcia', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 29, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 50, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', 44, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 37, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 36, 'Estadunidense', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', 28, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 30, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 57, 'Chinêsa', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 33, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Parda', 57, 'Portuguêsa', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Amarela', 41, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 25, 'Sul-africana', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', 36, 'Nigeriana', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', 46, 'Neozelandês', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', 44, 'Japonêsa', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 32, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 43, 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 33, 'Estadunidense', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 58, 'Chinêsa', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 44, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 26, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', 36, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 56, 'Indiana', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', 59, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 37, 'Argentina', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 57, 'Neozelandês', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Outra', 57, 'Australiana', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', 40, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 35, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 25, 'Russa', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', 60, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 52, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 42, 'Estadunidense', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 25, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', 26, 'Canadense', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 40, 'Portuguêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 27, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 31, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 59, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 53, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 54, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 33, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 38, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 29, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 36, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 31, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Preta', 46, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Preta', 30, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 26, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 34, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 31, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Outra', 56, 'Argentina', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', 38, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Preta', 52, 'Russa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 33, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 57, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', 43, 'Indiana', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', 34, 'Argentina', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 40, 'Argentina', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 55, 'Indiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 57, 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 53, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 56, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 27, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', 44, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', 44, 'Canadense', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 31, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Branca', 28, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', 57, 'Espanhola', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 58, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 29, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 54, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 38, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', 35, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 38, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Branca', 48, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 50, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 31, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 36, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Branca', 40, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', 40, 'Chinêsa', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 56, 'Japonêsa', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', 46, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 38, 'Italiana', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', 36, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 33, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', 25, 'Italiana', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 53, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Indígena', 42, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 57, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 37, 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Branca', 44, 'Argentina', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Indígena', 30, 'Espanhola', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 48, 'Alemã', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 25, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', 39, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 57, 'Russa', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', 25, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 60, 'Egípcia', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 35, 'Estadunidense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 29, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', 52, 'Chilena', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', 46, 'Neozelandês', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Outra', 49, 'Sul-africana', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', 36, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 36, 'Alemã', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 42, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', 60, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 47, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Outra', 60, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Preta', 48, 'Russa', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 40, 'Portuguêsa', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Preta', 27, 'Espanhola', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 46, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 53, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 47, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Parda', 48, 'Canadense', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 34, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 55, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', 43, 'Portuguêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 55, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 42, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 26, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 48, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 48, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 57, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', 47, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Amarela', 45, 'Estadunidense', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 41, 'Estadunidense', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 29, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 59, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 45, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 43, 'Neozelandês', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 46, 'Indiana', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 55, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 44, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 25, 'Argentina', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Indígena', 48, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', 36, 'Neozelandês', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 43, 'Indiana', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', 54, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 54, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Preta', 54, 'Mexicana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', 42, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', 34, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 36, 'Nigeriana', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 56, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 48, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 51, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 26, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 51, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 47, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', 40, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 34, 'Nigeriana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 49, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', 55, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 49, 'Indiana', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 48, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 60, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Parda', 38, 'Mexicana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', 60, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 56, 'Russa', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', 55, 'Sul-africana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Indígena', 53, 'Francês', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 59, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 42, 'Estadunidense', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 45, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 60, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 59, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 39, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 43, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 59, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', 44, 'Espanhola', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', 58, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 37, 'Portuguêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 34, 'Portuguêsa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 50, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Outra', 31, 'Chinêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 41, 'Mexicana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Branca', 28, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 58, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 27, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 49, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 33, 'Portuguêsa', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 60, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Amarela', 60, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 35, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 34, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Branca', 45, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', 44, 'Neozelandês', 'Mestrado', 'Tempo Integral'),
('Outro', 'Indígena', 31, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Indígena', 39, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', 34, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 34, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 44, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 50, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 35, 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 48, 'Japonêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 29, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 53, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', 28, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Branca', 38, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', 57, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 27, 'Estadunidense', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', 47, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 43, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 43, 'Argentina', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', 37, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 59, 'Japonêsa', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 29, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 49, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Parda', 36, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 39, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 30, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 40, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Branca', 39, 'Espanhola', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', 57, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 54, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 34, 'Sul-africana', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 51, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Branca', 58, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Indígena', 26, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Branca', 57, 'Nigeriana', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 33, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 35, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 52, 'Espanhola', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 50, 'Chilena', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', 29, 'Mexicana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', 43, 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', 55, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 39, 'Mexicana', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 32, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Parda', 28, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 42, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 57, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 43, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 58, 'Chinêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 39, 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', 52, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 40, 'Egípcia', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 53, 'Espanhola', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 56, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 39, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', 34, 'Portuguêsa', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', 42, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 34, 'Sul-africana', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', 30, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 29, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 33, 'Egípcia', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', 45, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 44, 'Chinêsa', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', 60, 'Egípcia', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 38, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 40, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Preta', 35, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 60, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 47, 'Russa', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 45, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Outro', 'Indígena', 31, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 29, 'Espanhola', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 36, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 54, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', 52, 'Espanhola', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 36, 'Egípcia', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Indígena', 48, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', 53, 'Estadunidense', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 28, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', 35, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 43, 'Chinêsa', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Branca', 48, 'Russa', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Preta', 58, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 60, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Indígena', 51, 'Francês', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 37, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 38, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', 27, 'Alemã', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', 47, 'Francês', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 54, 'Estadunidense', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 50, 'Estadunidense', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Branca', 51, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 45, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Preta', 43, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 30, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 38, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 42, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 40, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Preta', 55, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Branca', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Preta', 52, 'Alemã', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 47, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Branca', 50, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', 28, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 44, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 32, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Indígena', 41, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 59, 'Italiana', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Amarela', 35, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 41, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 47, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Preta', 50, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 60, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Amarela', 55, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Outra', 48, 'Neozelandês', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 35, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Outra', 37, 'Canadense', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Amarela', 41, 'Chilena', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 35, 'Canadense', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 58, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', 40, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Outra', 56, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 59, 'Canadense', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 49, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 26, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 34, 'Australiana', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 28, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 58, 'Japonêsa', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Branca', 26, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 52, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 28, 'Neozelandês', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', 30, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Branca', 49, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Branca', 34, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', 60, 'Egípcia', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 39, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 50, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 36, 'Espanhola', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 43, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', 58, 'Italiana', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 55, 'Portuguêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 26, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 27, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 40, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', 32, 'Sul-africana', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 29, 'Estadunidense', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', 33, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Outro', 'Indígena', 54, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 31, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 44, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', 30, 'Nigeriana', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 31, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Outra', 45, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', 50, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Outra', 36, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 48, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Indígena', 57, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Preta', 33, 'Francês', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Preta', 36, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Indígena', 36, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Outra', 59, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Branca', 51, 'Estadunidense', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Parda', 48, 'Chinêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Preta', 54, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 60, 'Chilena', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 46, 'Canadense', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 60, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', 42, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 25, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 31, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Preta', 45, 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 44, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 29, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 50, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Preta', 40, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 30, 'Portuguêsa', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 44, 'Portuguêsa', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 52, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 60, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Preta', 43, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 56, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Indígena', 31, 'Neozelandês', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 51, 'Francês', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', 51, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Outra', 25, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 33, 'Japonêsa', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Preta', 44, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 25, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher transgênero', 'Branca', 49, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Branca', 26, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', 41, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 44, 'Egípcia', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Indígena', 48, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 49, 'Mexicana', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Indígena', 39, 'Russa', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', 53, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 41, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Amarela', 34, 'Sul-africana', 'Mestrado', 'Tempo Integral'),
('Outro', 'Amarela', 54, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 59, 'Mexicana', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Parda', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 49, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Amarela', 28, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 51, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Amarela', 36, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 36, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Preta', 31, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Preta', 47, 'Argentina', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 43, 'Italiana', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Branca', 52, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', 41, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Outra', 31, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Outra', 48, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Outra', 43, 'Mexicana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Preta', 51, 'Portuguêsa', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 59, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 42, 'Australiana', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Preta', 39, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Preta', 47, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 53, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Outra', 53, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Amarela', 39, 'Canadense', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 29, 'Portuguêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Parda', 52, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Gênero fluido', 'Indígena', 26, 'Canadense', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', 25, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', 50, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Mulher transgênero', 'Parda', 56, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Não-binário', 'Preta', 59, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 33, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Indígena', 45, 'Francês', 'Mestrado', 'Tempo Integral'),
('Gênero fluido', 'Parda', 31, 'Sul-africana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', 42, 'Nigeriana', 'Mestrado', 'Tempo Parcial'),
('Mulher cisgênero', 'Amarela', 27, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem transgênero', 'Amarela', 32, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Amarela', 44, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 52, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Preta', 42, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', 29, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Outro', 'Branca', 49, 'Argentina', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Parda', 47, 'Russa', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Indígena', 54, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Não-binário', 'Outra', 37, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Gênero fluido', 'Branca', 47, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Outro', 'Outra', 30, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Preta', 58, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Outra', 44, 'Portuguêsa', 'Doutorado', 'Tempo Parcial'),
('Não-binário', 'Branca', 44, 'Russa', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 50, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Outra', 51, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 31, 'Indiana', 'Pós-doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 52, 'Mexicana', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Outra', 43, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Parda', 37, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 33, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Parda', 32, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Amarela', 49, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Outro', 'Outra', 39, 'Nigeriana', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', 35, 'Argentina', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 58, 'Nigeriana', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Parda', 39, 'Brasileira', 'Pós-doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Parda', 60, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 43, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Branca', 28, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Parda', 27, 'Russa', 'Mestrado', 'Tempo Integral'),
('Mulher transgênero', 'Outra', 57, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 35, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 27, 'Indiana', 'Mestrado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 34, 'Japonêsa', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Amarela', 40, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Amarela', 41, 'Francês', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Branca', 48, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Amarela', 42, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Parda', 40, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Não-binário', 'Indígena', 53, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', 56, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Parda', 28, 'Russa', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher transgênero', 'Indígena', 48, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', 58, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Outra', 44, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', 53, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Não-binário', 'Indígena', 41, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Outro', 'Branca', 47, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem cisgênero', 'Outra', 25, 'Alemã', 'Mestrado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Outra', 40, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Outro', 'Preta', 53, 'Estadunidense', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Indígena', 39, 'Espanhola', 'Doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 54, 'Nigeriana', 'Pós-doutorado', 'Tempo Parcial'),
('Gênero fluido', 'Outra', 44, 'Sul-africana', 'Mestrado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 47, 'Egípcia', 'Doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 30, 'Japonêsa', 'Pós-doutorado', 'Tempo Parcial'),
('Não-binário', 'Indígena', 28, 'Brasileira', 'Doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', 54, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem transgênero', 'Parda', 41, 'Brasileira', 'Mestrado', 'Dedicação Exclusiva'),
('Homem transgênero', 'Parda', 26, 'Estadunidense', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Outra', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 25, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Homem cisgênero', 'Branca', 25, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Homem cisgênero', 'Amarela', 25, 'Brasileira', 'Doutorado', 'Tempo Parcial'),
('Mulher cisgênero', 'Indígena', 32, 'Argentina', 'Doutorado', 'Dedicação Exclusiva'),
('Outro', 'Indígena', 56, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Outro', 'Branca', 34, 'Canadense', 'Mestrado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', 42, 'Brasileira', 'Pós-doutorado', 'Tempo Integral'),
('Homem transgênero', 'Indígena', 32, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Branca', 53, 'Chinêsa', 'Doutorado', 'Tempo Integral'),
('Não-binário', 'Parda', 27, 'Brasileira', 'Mestrado', 'Tempo Integral'),
('Homem transgênero', 'Outra', 33, 'Sul-africana', 'Mestrado', 'Dedicação Exclusiva'),
('Gênero fluido', 'Amarela', 25, 'Brasileira', 'Mestrado', 'Tempo Parcial'),
('Homem transgênero', 'Amarela', 37, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher cisgênero', 'Parda', 34, 'Italiana', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Parda', 25, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Mulher transgênero', 'Amarela', 26, 'Brasileira', 'Pós-doutorado', 'Dedicação Exclusiva'),
('Mulher cisgênero', 'Indígena', 36, 'Brasileira', 'Doutorado', 'Tempo Integral'),
('Gênero fluido', 'Indígena', 33, 'Brasileira', 'Doutorado', 'Tempo Integral');
