INSERT INTO infraestrutura (tipo, quantidade, nome_ies, uf_ies, municipio_ies) VALUES 
('Biblioteca digital', 2, 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Sala de dança', 5, 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Centro de pesquisa multidisciplinar', 3, 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Laboratório de informática', 48, 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Piscina olímpica', 2, 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Laboratório de prototipagem', 1, 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Centro de simulação médica', 3, 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Academia de ginástica', 3, 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Quadra de basquete', 3, 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Laboratório de arquitetura', 3, 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Pista de atletismo', 2, 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Laboratório de engenharia elétrica', 6, 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Lanchonete', 5, 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Galeria de arte', 2, 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Quadra de futebol', 3, 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Sala de artes marciais', 1, 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Estúdio de gravação', 2, 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Pista de atletismo', 1, 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Anfiteatro', 2, 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Museu universitário', 2, 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Academia de ginástica', 1, 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Anfiteatro', 1, 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Laboratório de biologia', 8, 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Biblioteca digital', 1, 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Parque tecnológico', 2, 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Laboratório de arquitetura', 2, 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Laboratório de realidade virtual e aumentada', 1, 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Laboratório de robótica', 4, 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Biblioteca digital', 1, 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Centro de inovação e startups', 1, 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Laboratório de prototipagem', 5, 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Laboratório maker', 4, 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Restaurante universitário', 1, 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Sala de aula invertida', 13, 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Laboratório de química', 6, 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Centro de pesquisa multidisciplinar', 3, 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Sala de aula tradicional', 34, 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Laboratório de química', 19, 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Quadra de vôlei', 5, 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Laboratório de arquitetura', 1, 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Sala de cinema', 1, 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Quadra de futebol', 3, 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Laboratório de engenharia elétrica', 10, 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Laboratório de idiomas', 19, 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Academia de ginástica', 3, 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Galeria de arte', 1, 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Laboratório de informática', 6, 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Centro de pesquisa multidisciplinar', 3, 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Centro de inovação e startups', 2, 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Laboratório de biologia', 18, 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Laboratório de análise de dados', 7, 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Estúdio de gravação', 2, 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Sala de dança', 2, 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Arquivo histórico', 1, 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Quadra de vôlei', 4, 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Centro de simulação médica', 3, 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Laboratório de inteligência artificial', 3, 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Quadra de vôlei', 3, 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Sala de aula tradicional', 56, 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Restaurante universitário', 1, 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Sala de aula tradicional', 183, 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Campo de golfe', 1, 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Centro de simulação médica', 4, 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Sala de coworking', 4, 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Sala de jogos', 2, 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Sala de cinema', 2, 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Laboratório maker', 4, 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Academia de ginástica', 2, 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Auditório para eventos culturais', 1, 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Sala de jogos', 1, 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Laboratório de inteligência artificial', 2, 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Sala de artes marciais', 1, 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Centro de simulação médica', 4, 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Sala de coworking', 4, 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Sala de dança', 2, 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Laboratório de realidade virtual e aumentada', 2, 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Sala de aula invertida', 9, 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Restaurante universitário', 2, 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Laboratório de engenharia mecânica', 4, 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Quadra de futebol', 5, 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Laboratório de prototipagem', 3, 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Praça de alimentação', 3, 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Laboratório de arquitetura', 2, 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Parque tecnológico', 2, 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Laboratório de arquitetura', 4, 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Biblioteca física', 2, 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Arquivo histórico', 1, 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Quadra de basquete', 3, 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Restaurante universitário', 2, 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Galeria de arte', 2, 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Sala de jogos', 2, 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Centro de inovação e startups', 1, 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Arquivo histórico', 2, 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Sala de dança', 5, 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Laboratório de análise de dados', 4, 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Estúdio de gravação', 2, 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Cafeteria', 2, 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Biblioteca física', 3, 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Arquivo histórico', 2, 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Arquivo histórico', 1, 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Laboratório de realidade virtual e aumentada', 5, 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Auditório', 1, 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Campo de golfe', 0, 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Laboratório de arquitetura', 1, 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Sala de coworking', 1, 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Laboratório de química', 15, 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Auditório para eventos culturais', 4, 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Sala de coworking', 10, 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Quadra de vôlei', 2, 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Laboratório de análise de dados', 3, 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Sala de aula invertida', 9, 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Academia de ginástica', 2, 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Auditório para eventos culturais', 2, 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Laboratório de química', 10, 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Biblioteca digital', 2, 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Praça de alimentação', 1, 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Sala de aula tradicional', 263, 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Sala de aula tradicional', 189, 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Centro cultural', 2, 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Laboratório de arquitetura', 3, 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Biblioteca digital', 1, 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Restaurante universitário', 5, 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Sala de jogos', 2, 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Restaurante universitário', 2, 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Laboratório de análise de dados', 3, 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Centro de pesquisa multidisciplinar', 3, 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Laboratório de robótica', 7, 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Quadra de vôlei', 3, 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Sala de artes marciais', 1, 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Centro cultural', 2, 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Laboratório de design gráfico', 1, 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Laboratório de informática', 30, 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Centro cultural', 1, 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Biblioteca física', 3, 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Laboratório de idiomas', 14, 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Laboratório de engenharia mecânica', 5, 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Incubadora de empresas', 1, 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Sala de aula invertida', 11, 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Lanchonete', 2, 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Estúdio de gravação', 2, 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Incubadora de empresas', 2, 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Laboratório de inteligência artificial', 3, 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Sala de coworking', 10, 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Sala de artes marciais', 2, 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Parque tecnológico', 1, 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Piscina olímpica', 1, 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Sala de cinema', 2, 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Laboratório de informática', 44, 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Laboratório de realidade virtual e aumentada', 1, 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Pista de atletismo', 2, 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Sala de jogos', 3, 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Sala de coworking', 6, 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Laboratório de biologia', 15, 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Laboratório de design gráfico', 4, 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Quadra de basquete', 4, 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Laboratório de prototipagem', 1, 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Laboratório de inteligência artificial', 2, 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Lanchonete', 8, 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Laboratório de engenharia mecânica', 6, 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Restaurante universitário', 1, 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Lanchonete', 6, 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Laboratório de análise de dados', 2, 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Estúdio de gravação', 1, 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Incubadora de empresas', 2, 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Quadra de vôlei', 4, 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Incubadora de empresas', 1, 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Pista de atletismo', 2, 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Centro de pesquisa multidisciplinar', 1, 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Parque tecnológico', 2, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Estúdio de gravação', 5, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Auditório', 4, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Lanchonete', 2, 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Biblioteca física', 3, 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Auditório para eventos culturais', 3, 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Centro cultural', 2, 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Laboratório de design gráfico', 8, 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Piscina olímpica', 1, 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Auditório para eventos culturais', 5, 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Centro de pesquisa multidisciplinar', 3, 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Campo de golfe', 1, 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Laboratório de arquitetura', 1, 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Anfiteatro', 4, 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Auditório para eventos culturais', 2, 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Sala de dança', 2, 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Laboratório de biologia', 18, 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Sala de coworking', 7, 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Quadra de vôlei', 5, 'Centro Universitário LS', 'DF', 'Brasília'),
('Laboratório de engenharia mecânica', 10, 'Centro Universitário LS', 'DF', 'Brasília'),
('Laboratório de idiomas', 7, 'Centro Universitário LS', 'DF', 'Brasília'),
('Laboratório de design gráfico', 9, 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Pista de atletismo', 2, 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Auditório', 3, 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Sala de aula invertida', 46, 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Biblioteca física', 2, 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Laboratório de biologia', 8, 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Restaurante universitário', 4, 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Pista de atletismo', 1, 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Laboratório de realidade virtual e aumentada', 5, 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Biblioteca física', 2, 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Laboratório de prototipagem', 5, 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Sala de aula tradicional', 35, 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Pista de atletismo', 1, 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Laboratório de robótica', 1, 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Centro de pesquisa multidisciplinar', 1, 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Parque tecnológico', 1, 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Centro cultural', 2, 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Piscina olímpica', 1, 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Sala de artes marciais', 2, 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Praça de alimentação', 2, 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Centro cultural', 2, 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Laboratório de biologia', 13, 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Laboratório de robótica', 6, 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Ginásio poliesportivo', 1, 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Laboratório de arquitetura', 3, 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Laboratório de física', 8, 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Laboratório de análise de dados', 4, 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Centro de pesquisa multidisciplinar', 3, 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Laboratório de inteligência artificial', 2, 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Sala de aula invertida', 9, 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Biblioteca física', 2, 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Estúdio de gravação', 3, 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Academia de ginástica', 3, 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Laboratório maker', 1, 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Laboratório de química', 13, 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Estúdio de gravação', 3, 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Laboratório de inteligência artificial', 3, 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Laboratório de engenharia elétrica', 10, 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Laboratório de prototipagem', 2, 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Quadra de vôlei', 2, 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Laboratório de realidade virtual e aumentada', 4, 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Laboratório maker', 1, 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Museu universitário', 1, 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Biblioteca física', 3, 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Laboratório de inteligência artificial', 3, 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Campo de golfe', 0, 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Biblioteca digital', 2, 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Quadra de futebol', 3, 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Sala de jogos', 1, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Laboratório de robótica', 10, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Quadra de basquete', 3, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Arquivo histórico', 1, 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Auditório', 8, 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Laboratório de arquitetura', 3, 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Sala de jogos', 3, 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Sala de cinema', 1, 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Laboratório de informática', 23, 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Laboratório de química', 9, 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Parque tecnológico', 2, 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Restaurante universitário', 1, 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Laboratório de engenharia mecânica', 1, 'Faculdade Alpha', 'PE', 'Recife'),
('Auditório para eventos culturais', 2, 'Faculdade Alpha', 'PE', 'Recife'),
('Laboratório de design gráfico', 4, 'Faculdade Alpha', 'PE', 'Recife'),
('Piscina olímpica', 1, 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Sala de jogos', 3, 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Anfiteatro', 2, 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Auditório para eventos culturais', 2, 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Restaurante universitário', 5, 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Laboratório de idiomas', 3, 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Laboratório de realidade virtual e aumentada', 5, 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Laboratório de física', 7, 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Sala de aula invertida', 19, 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Sala de aula tradicional', 256, 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Anfiteatro', 3, 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Laboratório de idiomas', 6, 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Centro de inovação e startups', 2, 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Auditório', 7, 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Quadra de vôlei', 2, 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Quadra de basquete', 2, 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Laboratório de física', 7, 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Laboratório de engenharia elétrica', 4, 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Arquivo histórico', 1, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Quadra de basquete', 2, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Laboratório de prototipagem', 2, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Laboratório de biologia', 7, 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Campo de golfe', 1, 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Auditório para eventos culturais', 1, 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Laboratório de prototipagem', 2, 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Laboratório de inteligência artificial', 1, 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Ginásio poliesportivo', 3, 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Sala de dança', 1, 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Pista de atletismo', 2, 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Incubadora de empresas', 2, 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Sala de cinema', 1, 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Centro cultural', 2, 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Incubadora de empresas', 2, 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Sala de artes marciais', 3, 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Laboratório de informática', 5, 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Cafeteria', 4, 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Restaurante universitário', 2, 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Laboratório de análise de dados', 10, 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Academia de ginástica', 3, 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Laboratório de prototipagem', 1, 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Quadra de futebol', 5, 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Quadra de basquete', 3, 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Lanchonete', 4, 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Sala de artes marciais', 2, 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Laboratório maker', 3, 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Centro de simulação médica', 5, 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Laboratório de arquitetura', 1, 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Parque tecnológico', 1, 'FACULDADE DE SOBRAL', 'CE', 'Sobral');