INSERT INTO cursos (nome, area, modalidade, grau_academico, mensalidade, nome_ies, uf_ies, municipio_ies) VALUES 
('Ciências Humanas - Sociologia', 'Educação', 'Presencial', 'Licenciatura', 1541, 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Coaching E Mentoring', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 3961, 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Licenciatura Intercultural - Ciências Da Natureza', 'Educação', 'Presencial', 'Licenciatura', 5487, 'UNIVERSIDADE CATÓLICA DE PERNAMBUCO', 'PE', 'Recife'),
('Ciências Exatas Com Habilitação Em Física', 'Educação', 'EaD', 'Licenciatura', 6043, 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Finanças E Negócios', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 3080, 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Devops', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Tecnólogo', 9325, 'Faculdade Anhanguera de Jaú', 'SP', 'Jaú'),
('Ciência Do Esporte', 'Saúde e bem-estar', 'Presencial', 'Bacharelado', 4709, 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Toxicologia Ambiental', 'Ciências naturais, matemática e estatística', 'EaD', 'Tecnólogo', 4280, 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Letras - Português E Polonês', 'Educação', 'Presencial', 'Licenciatura', 2696, 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Educação Física', 'Educação', 'EaD', 'Licenciatura', 4680, 'FACULDADE CURITIBANA', 'PR', 'Curitiba'),
('Produção Pesqueira', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Tecnólogo', 4457, 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Licenciatura Intercultural - Ciências Da Natureza', 'Educação', 'EaD', 'Licenciatura', 3638, 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Canto', 'Artes e humanidades', 'EaD', 'Bacharelado', 9477, 'UNIVERSIDADE ALTO VALE DO RIO DO PEIXE', 'SC', 'Caçador'),
('Música - Violino E Viola', 'Artes e humanidades', 'Presencial', 'Bacharelado', 7110, 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Estética', 'Serviços', 'Presencial', 'Bacharelado', 2836, 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Jornalismo Digital', 'Ciências sociais, comunicação e informação', 'Presencial', 'Bacharelado', 1920, 'FACULDADE ANHANGUERA DE CONTAGEM', 'MG', 'Contagem'),
('Ciência Dos Dados', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 2648, 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Música - Produção Musical', 'Artes e humanidades', 'EaD', 'Bacharelado', 3314, 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Letras - Árabe', 'Artes e humanidades', 'EaD', 'Bacharelado', 6309, 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Comunicação: Rádio, Televisão E Internet', 'Ciências sociais, comunicação e informação', 'Presencial', 'Bacharelado', 3279, 'FACULDADE VERDE NORTE', 'MG', 'Mato Verde'),
('Música - Produção Musical', 'Artes e humanidades', 'Presencial', 'Bacharelado', 1647, 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Gerontologia', 'Saúde e bem-estar', 'EaD', 'Tecnólogo', 6582, 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Ciências Biológicas: Biofísica', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 5952, 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Coaching', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 3122, 'Faculdade Cidade Teológica Pentecostal', 'CE', 'Fortaleza'),
('Produção Pesqueira', 'Agricultura, silvicultura, pesca e veterinária', 'Presencial', 'Tecnólogo', 5135, 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Letras - Japonês', 'Educação', 'Presencial', 'Licenciatura', 2920, 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Comunicação Empresarial', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 4736, 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Ciência Do Esporte', 'Saúde e bem-estar', 'EaD', 'Bacharelado', 1377, 'FACULDADE ÁGORA - FAG', 'MT', 'Campo Novo do Parecis'),
('Interdisciplinar Em Ciência E Tecnologia', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 8080, 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Tecnologias Educacionais', 'Educação', 'Presencial', 'Licenciatura', 5536, 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Música - Percussão', 'Artes e humanidades', 'Presencial', 'Bacharelado', 6754, 'STRONG BUSINESS SCHOOL', 'SP', 'Santo André'),
('Ciências Humanas - Sociologia', 'Educação', 'Presencial', 'Licenciatura', 9972, 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Gestão De Produto', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 1147, 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Letras - Latim', 'Educação', 'Presencial', 'Licenciatura', 2197, 'FACULDADES INTEGRADAS DE CIÊNCIAS HUMANAS, SAÚDE E EDUCAÇÃO DE GUARULHOS', 'SP', 'Guarulhos'),
('Línguas Estrangeiras Aplicadas Ao Multilinguismo E À Sociedade Da Informação', 'Artes e humanidades', 'Presencial', 'Bacharelado', 4753, 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Formação De Professores Indígenas', 'Educação', 'Presencial', 'Licenciatura', 8575, 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Estética E Cosmética', 'Serviços', 'Presencial', 'Tecnólogo', 1174, 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Sistemas Embarcados', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 7541, 'AFYA Faculdade de Ciências Médicas de Palmas', 'TO', 'Palmas'),
('Ciências Biológicas: Biofísica', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 6507, 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Engenharia Naval E Oceânica', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 3013, 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Letras - Línguas Adicionais Inglês, Espanhol E Respectivas Literaturas', 'Educação', 'Presencial', 'Licenciatura', 6729, 'Faculdade Multiversa de Fortaleza', 'CE', 'Fortaleza'),
('Letras - Latim', 'Educação', 'EaD', 'Licenciatura', 5205, 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Matemática Aplicada A Negócios', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 3000, 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Soldagem', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 1784, 'FACULDADES INTEGRADAS DE CASSILÂNDIA', 'MS', 'Cassilândia'),
('Coaching', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 5904, 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 5739, 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Letras - Línguas Adicionais Inglês, Espanhol E Respectivas Literaturas', 'Educação', 'Presencial', 'Licenciatura', 1591, 'UNIVERSIDADE FEEVALE', 'RS', 'Novo Hamburgo'),
('Engenharia Naval', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 8773, 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Matemática Aplicada A Negócios', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 8821, 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Design Industrial', 'Artes e humanidades', 'Presencial', 'Bacharelado', 4343, 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Gestão E Empreendedorismo', 'Educação', 'EaD', 'Licenciatura', 1319, 'UNIVERSIDADE FEDERAL DE PERNAMBUCO', 'PE', 'Recife'),
('Manutenção De Aeronave De Asas Rotativas', 'Serviços', 'EaD', 'Tecnólogo', 5088, 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Ciência De Dados E Inteligência Artificial', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Bacharelado', 3527, 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Inspeção De Equipamentos E De Soldagem', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 8278, 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Negócios Internacionais', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 1995, 'UNIVERSIDADE FEDERAL DO OESTE DA BAHIA', 'BA', 'Barreiras'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'EaD', 'Bacharelado', 7991, 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Engenharia Naval', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 4740, 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Estética E Cosmética', 'Serviços', 'EaD', 'Tecnólogo', 8414, 'FACULDADE EDUCACIONAL JURÍDICA E GERENCIAL DE OLIVEIRA', 'MG', 'Oliveira'),
('Ciências Exatas Com Habilitação Em Física', 'Educação', 'EaD', 'Licenciatura', 8076, 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Letras - Língua Portuguesa, Língua Inglesa E Suas Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 2427, 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Matemática Aplicada A Negócios', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 1998, 'FACULDADE HORIZONTINA', 'RS', 'Horizontina'),
('Ciências Exatas Com Habilitação Em Física', 'Educação', 'Presencial', 'Licenciatura', 4123, 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Matemática Computacional', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 4641, 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'Presencial', 'Licenciatura', 7339, 'Faculdade Católica Cavanis do Sudoeste do Pará', 'PA', 'Novo Progresso'),
('Engenharia Naval', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 1703, 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Manutenção De Aeronave De Asas Rotativas', 'Serviços', 'Presencial', 'Tecnólogo', 8895, 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Ciência De Dados E Inteligência Artificial', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Bacharelado', 2680, 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Design Industrial', 'Artes e humanidades', 'Presencial', 'Bacharelado', 8013, 'UNIVERSIDADE ESTADUAL DE GOIÁS', 'GO', 'Anápolis'),
('Estética', 'Serviços', 'EaD', 'Bacharelado', 2504, 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Letras - Latim', 'Educação', 'Presencial', 'Licenciatura', 7704, 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Ciências Humanas - Sociologia', 'Educação', 'EaD', 'Licenciatura', 8327, 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Produção Pesqueira', 'Agricultura, silvicultura, pesca e veterinária', 'Presencial', 'Tecnólogo', 4283, 'UNIVERSIDADE ESTADUAL DE CAMPINAS', 'SP', 'Campinas'),
('Canto', 'Artes e humanidades', 'EaD', 'Bacharelado', 7838, 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Têxtil E Moda', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 5049, 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Design Visual', 'Artes e humanidades', 'EaD', 'Bacharelado', 1943, 'Escola de Sargentos de Logística', 'RJ', 'Rio de Janeiro'),
('Ciência Dos Dados', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 9433, 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Gerontologia', 'Saúde e bem-estar', 'EaD', 'Tecnólogo', 1460, 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Inspeção De Equipamentos E De Soldagem', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 5240, 'Instituto Una de Itabira', 'MG', 'Itabira'),
('Letras - Línguas Adicionais Inglês, Espanhol E Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 2989, 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Estética', 'Serviços', 'Presencial', 'Bacharelado', 1960, 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Gestão De Negócios', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 1884, 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Coaching', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 4241, 'ESCOLA DA CIDADE - FACULDADE DE ARQUITETURA E URBANISMO', 'SP', 'São Paulo'),
('Engenharia De Instrumentação, Automação E Robótica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 6769, 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Gestão Ambiental E Sustentabilidade', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 8238, 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Engenharia Ambiental E Energias Renováveis', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 1708, 'Faculdade UNA de Itumbiara', 'GO', 'Itumbiara'),
('Têxtil E Moda', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 7189, 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Criação Digital', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Bacharelado', 6577, 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Inspeção De Equipamentos E De Soldagem', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 4825, 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Letras - Português-Inglês', 'Educação', 'EaD', 'Licenciatura', 9967, 'Escola Superior de Pouso Alegre', 'MG', 'Pouso Alegre'),
('Design Digital', 'Artes e humanidades', 'EaD', 'Bacharelado', 8495, 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Administração', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 3307, 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Finanças E Negócios', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 7533, 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Aqüicultura', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Tecnólogo', 8504, 'FACULDADE BATISTA BRASILEIRA', 'BA', 'Salvador'),
('Matemática Aplicada E Computacional Com Habilitação Em Métodos Matemáticos', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 7882, 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Produção Pesqueira', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Tecnólogo', 4174, 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Ciências Humanas - Sociologia', 'Educação', 'Presencial', 'Licenciatura', 9311, 'Faculdade Anhanguera de Palmas', 'TO', 'Palmas'),
('Música - Violino E Viola', 'Artes e humanidades', 'Presencial', 'Bacharelado', 2642, 'Centro Universitário LS', 'DF', 'Brasília'),
('Têxtil E Moda', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 3557, 'Centro Universitário LS', 'DF', 'Brasília'),
('Gestão E Empreendedorismo', 'Educação', 'Presencial', 'Licenciatura', 1696, 'Centro Universitário LS', 'DF', 'Brasília'),
('Design De Produto E Serviço', 'Artes e humanidades', 'Presencial', 'Bacharelado', 8724, 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Estética', 'Serviços', 'EaD', 'Bacharelado', 3902, 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Inspeção De Equipamentos E De Soldagem', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 8758, 'FACULDADE DE TECNOLOGIA DE BOTUCATU', 'SP', 'Botucatu'),
('Finanças E Negócios', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 9013, 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Ciências Humanas - Sociologia', 'Educação', 'Presencial', 'Licenciatura', 5647, 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Matemática Computacional', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 5559, 'FACULDADE DE HORTOLÂNDIA', 'SP', 'Hortolândia'),
('Interdisciplinar Em Ciência E Tecnologia', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 9738, 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Design Industrial', 'Artes e humanidades', 'Presencial', 'Bacharelado', 8336, 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Biotecnologia', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 9928, 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Letras: Espanhol', 'Educação', 'EaD', 'Licenciatura', 9890, 'Faculdade Anhanguera De Divinópolis', 'MG', 'Divinópolis'),
('Jornalismo Digital', 'Ciências sociais, comunicação e informação', 'Presencial', 'Bacharelado', 6370, 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Interdisciplinar Em Ciência E Tecnologia', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 6322, 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 8014, 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Design De Produto E Serviço', 'Artes e humanidades', 'Presencial', 'Bacharelado', 6096, 'Faculdade Life Unic Education', 'SC', 'Joinville'),
('Produção Pesqueira', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Tecnólogo', 7131, 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Negócios Internacionais', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 5092, 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Música - Produção Musical', 'Artes e humanidades', 'EaD', 'Bacharelado', 9300, 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Ciência De Dados E Inteligência Artificial', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Bacharelado', 5948, 'Faculdade de Tecnologia da Amazônia', 'AM', 'Manaus'),
('Gestão De Negócios', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 7635, 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Formação De Professores Indígenas', 'Educação', 'EaD', 'Licenciatura', 9662, 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Letras - Latim', 'Educação', 'EaD', 'Licenciatura', 9974, 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Canto', 'Artes e humanidades', 'EaD', 'Bacharelado', 7234, 'CENTRO UNIVERSITÁRIO DE VOLTA REDONDA', 'RJ', 'Volta Redonda'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'EaD', 'Bacharelado', 2998, 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Ciências Atuariais', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 4536, 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Letras: Espanhol', 'Educação', 'EaD', 'Licenciatura', 1802, 'FACULDADE DOS CERRADOS PIAUIENSES', 'PI', 'Corrente'),
('Manutenção De Aeronave De Asas Rotativas', 'Serviços', 'EaD', 'Tecnólogo', 8806, 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Letras: Inglês', 'Educação', 'Presencial', 'Licenciatura', 2962, 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Ciências Humanas - Sociologia', 'Educação', 'EaD', 'Licenciatura', 8862, 'FACULDADE DE ENSINO SUPERIOR DO INTERIOR PAULISTA', 'SP', 'Marília'),
('Engenharia Naval', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 3927, 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Gestão De Negócios', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 9632, 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Engenharia Mecânica Aeronáutica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 7516, 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Engenharia Naval E Oceânica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 2020, 'INSTITUTO SUPERIOR DE EDUCAÇÃO ATENEU', 'ES', 'Vila Velha'),
('Letras - Latim', 'Educação', 'Presencial', 'Licenciatura', 6280, 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Coaching', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 7331, 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Ciências Exatas Com Habilitação Em Física', 'Educação', 'Presencial', 'Licenciatura', 3721, 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Design Visual', 'Artes e humanidades', 'Presencial', 'Bacharelado', 2688, 'FACULDADE DE CIÊNCIAS JURÍDICAS DE SANTA MARIA', 'RS', 'Santa Maria'),
('Licenciatura Intercultural - Ciências Da Natureza', 'Educação', 'EaD', 'Licenciatura', 5915, 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Matemática Computacional', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 1181, 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Letras: Espanhol', 'Educação', 'Presencial', 'Licenciatura', 4012, 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Matemática Aplicada A Negócios', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 8021, 'UNIVERSIDADE FRANCISCANA', 'RS', 'Santa Maria'),
('Gestão Financeira', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 6453, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Desenvolvimento Rural E Gestão Agroindustrial', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Bacharelado', 8004, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Comunicação Empresarial', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 9019, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO RIO GRANDE DO SUL', 'RS', 'Bento Gonçalves'),
('Interdisciplinar Em Saúde', 'Saúde e bem-estar', 'Presencial', 'Bacharelado', 3133, 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Licenciatura Intercultural - Ciências Da Natureza', 'Educação', 'Presencial', 'Licenciatura', 2758, 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Toxicologia Ambiental', 'Ciências naturais, matemática e estatística', 'Presencial', 'Tecnólogo', 6176, 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Línguas Estrangeiras Aplicadas Ao Multilinguismo E À Sociedade Da Informação', 'Artes e humanidades', 'Presencial', 'Bacharelado', 1513, 'FACULDADE DE EDUCAÇÃO SUPERIOR DE PERNAMBUCO', 'PE', 'Petrolina'),
('Ciência Do Esporte', 'Saúde e bem-estar', 'Presencial', 'Bacharelado', 9228, 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Letras - Japonês', 'Educação', 'EaD', 'Licenciatura', 8968, 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Inspeção De Equipamentos E De Soldagem', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 1189, 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Engenharia Ambiental E Urbana', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 5185, 'FACULDADE DE TECNOLOGIA DE MOCOCA', 'SP', 'Mococa'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 4413, 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Mediação Cultural - Artes E Letras', 'Artes e humanidades', 'EaD', 'Bacharelado', 8204, 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Matemática Aplicada A Negócios', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 8619, 'FACULDADE LUCIANO FEIJÃO', 'CE', 'Sobral'),
('Gestão Financeira', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 5222, 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Processos Escolares', 'Educação', 'Presencial', 'Tecnólogo', 7520, 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Letras: Espanhol', 'Educação', 'Presencial', 'Licenciatura', 7522, 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Sistemas Embarcados', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 6257, 'CENTRO UNIVERSITÁRIO MAURÍCIO DE NASSAU DE CACOAL', 'RO', 'Cacoal'),
('Negócios Internacionais', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 2983, 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Música - Percussão', 'Artes e humanidades', 'EaD', 'Bacharelado', 5000, 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Gestão Financeira', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 6880, 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Licenciatura Intercultural - Ciências Da Natureza', 'Educação', 'EaD', 'Licenciatura', 1330, 'FACULDADE DE TECNOLOGIA DE OURINHOS', 'SP', 'Ourinhos'),
('Matemática Aplicada E Computacional Com Habilitação Em Métodos Matemáticos', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 1678, 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Letras: Espanhol', 'Educação', 'EaD', 'Licenciatura', 9903, 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Gestão De Negócios', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 5743, 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Mediação Cultural - Artes E Letras', 'Artes e humanidades', 'EaD', 'Bacharelado', 9433, 'FACULDADE UNINASSAU SOBRAL', 'CE', 'Sobral'),
('Engenharia De Instrumentação, Automação E Robótica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 8342, 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Produção Pesqueira', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Tecnólogo', 8595, 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Tecnologias Educacionais', 'Educação', 'Presencial', 'Licenciatura', 6894, 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Canto', 'Artes e humanidades', 'EaD', 'Bacharelado', 8270, 'INSTITUTO APHONSIANO DE ENSINO SUPERIOR', 'GO', 'Trindade'),
('Soldagem', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 5718, 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Coaching', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 3306, 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Criação Digital', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Bacharelado', 2358, 'Faculdades de Ciências e Tecnologia do Nordeste LTDA', 'CE', 'Fortaleza'),
('Letras - Japonês', 'Educação', 'EaD', 'Licenciatura', 4019, 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Mediação Cultural - Artes E Letras', 'Artes e humanidades', 'Presencial', 'Bacharelado', 4140, 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'Presencial', 'Bacharelado', 2862, 'Faculdade de Educação Superior de Tangará da Serra', 'MT', 'Tangará da Serra'),
('Mediação Cultural - Artes E Letras', 'Artes e humanidades', 'Presencial', 'Bacharelado', 4300, 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Design De Produto E Serviço', 'Artes e humanidades', 'Presencial', 'Bacharelado', 1258, 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Engenharia Ambiental E Urbana', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 1500, 'FACULDADES INTEGRADAS IPITANGA', 'BA', 'Lauro de Freitas'),
('Gerontologia', 'Saúde e bem-estar', 'EaD', 'Tecnólogo', 5647, 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Jornalismo Digital', 'Ciências sociais, comunicação e informação', 'Presencial', 'Bacharelado', 1831, 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Matemática Aplicada E Computacional Com Habilitação Em Métodos Matemáticos', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 1540, 'CENTRO UNIVERSITÁRIO AUTÔNOMO DO BRASIL', 'PR', 'Curitiba'),
('Soldagem', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 3426, 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Gestão Ambiental E Sustentabilidade', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 9861, 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Gestão De Negócios', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 9048, 'FACUDADE IEDUCARE - FIED', 'CE', 'Tianguá'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 5257, 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Formação De Professores Indígenas', 'Educação', 'Presencial', 'Licenciatura', 1223, 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'Presencial', 'Bacharelado', 6461, 'Faculdade Barros Melo Recife', 'PE', 'Recife'),
('Devops', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 7914, 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Soldagem', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 1642, 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Interdisciplinar Em Saúde', 'Saúde e bem-estar', 'EaD', 'Bacharelado', 4791, 'Faculdade Santa Teresa', 'AM', 'Manaus'),
('Engenharia De Instrumentação, Automação E Robótica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 5273, 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Jornalismo Digital', 'Ciências sociais, comunicação e informação', 'Presencial', 'Bacharelado', 2288, 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Música - Percussão', 'Artes e humanidades', 'EaD', 'Bacharelado', 6617, 'AJES - FACULDADE DO VALE DO JURUENA', 'MT', 'Juína'),
('Ciências Biológicas: Biofísica', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 5098, 'Faculdade Alpha', 'PE', 'Recife'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'EaD', 'Bacharelado', 8548, 'Faculdade Alpha', 'PE', 'Recife'),
('Ciências Exatas Com Habilitação Em Física', 'Educação', 'Presencial', 'Licenciatura', 4316, 'Faculdade Alpha', 'PE', 'Recife'),
('Ciências Fundamentais Para A Saúde', 'Saúde e bem-estar', 'EaD', 'Bacharelado', 9356, 'Faculdade Alpha', 'PE', 'Recife'),
('Alimentos', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 3744, 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Gestão Do Agronegócio', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 1561, 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Engenharia Naval E Oceânica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 8998, 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Coaching', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 6151, 'UNIVERSIDADE ESTADUAL DE MATO GROSSO DO SUL', 'MS', 'Dourados'),
('Alimentos', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 1723, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Mediação Cultural - Artes E Letras', 'Artes e humanidades', 'Presencial', 'Bacharelado', 4540, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Aqüicultura', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Tecnólogo', 5565, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Letras - Língua E Literatura Japonesa', 'Educação', 'Presencial', 'Licenciatura', 9682, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO CEARÁ', 'CE', 'Fortaleza'),
('Licenciatura Intercultural - Ciências Da Natureza', 'Educação', 'EaD', 'Licenciatura', 4025, 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Letras - Língua Portuguesa, Língua Inglesa E Suas Respectivas Literaturas', 'Educação', 'Presencial', 'Licenciatura', 4452, 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Design Visual', 'Artes e humanidades', 'Presencial', 'Bacharelado', 9591, 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Engenharia Naval E Oceânica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 3195, 'FACULDADE DA ASSOCIAÇÃO BRASILIENSE DE EDUCAÇÃO', 'RS', 'Marau'),
('Coaching E Mentoring', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 2756, 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Letras - Latim', 'Educação', 'Presencial', 'Licenciatura', 3071, 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Gestão De Produto', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 4982, 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Design Digital', 'Artes e humanidades', 'Presencial', 'Bacharelado', 6100, 'FACULDADE DE SABARÁ', 'MG', 'Sabará'),
('Alimentos', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 7710, 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Gestão Ambiental E Sustentabilidade', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 7117, 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Pedagogia Em Educação Profissional E Tecnológica', 'Educação', 'Presencial', 'Licenciatura', 5045, 'FACULDADE PITÁGORAS UNOPAR DE CANINDÉ', 'CE', 'Canindé'),
('Letras - Japonês', 'Educação', 'EaD', 'Licenciatura', 1317, 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Letras - Língua Portuguesa, Língua Inglesa E Suas Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 9901, 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Ciência Do Esporte', 'Saúde e bem-estar', 'EaD', 'Bacharelado', 5936, 'Faculdade de Medicina de Olinda', 'PE', 'Olinda'),
('Canto', 'Artes e humanidades', 'EaD', 'Bacharelado', 6715, 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Ciências Exatas Com Habilitação Em Física', 'Educação', 'EaD', 'Licenciatura', 2488, 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Soldagem', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 2993, 'Escola de Ensino Superior do Agreste Paraibano', 'PB', 'Guarabira'),
('Jornalismo Digital', 'Ciências sociais, comunicação e informação', 'EaD', 'Bacharelado', 9842, 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Pedagogia Em Educação Profissional E Tecnológica', 'Educação', 'Presencial', 'Licenciatura', 6867, 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Negócios Internacionais', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 3760, 'FACULDADE DE VIÇOSA', 'MG', 'Viçosa'),
('Engenharia Naval', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 2533, 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Música - Produção Musical', 'Artes e humanidades', 'EaD', 'Bacharelado', 2789, 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Música - Violino E Viola', 'Artes e humanidades', 'EaD', 'Bacharelado', 7429, 'ESCOLA DE ENGENHARIA KENNEDY', 'MG', 'Belo Horizonte'),
('Administração', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 8706, 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Gestão Ambiental E Sustentabilidade', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 9542, 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Interdisciplinar Em Ciência E Tecnologia', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 1034, 'FACULDADE DE SOBRAL', 'CE', 'Sobral'),
('Matemática Aplicada E Computacional Com Habilitação Em Métodos Matemáticos', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 5073, 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Letras: Espanhol', 'Educação', 'Presencial', 'Licenciatura', 3622, 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Desenvolvimento De Produtos Plásticos', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 4063, 'FACULDADE HÉLIO ROCHA', 'BA', 'Salvador'),
('Ciências Atuariais', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 6002, 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Música - Produção Musical', 'Artes e humanidades', 'EaD', 'Bacharelado', 2236, 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Engenharia Ambiental E Urbana', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 8467, 'FACULDADE RIO PARNAÍBA', 'MA', 'Timon'),
('Desenvolvimento Rural E Gestão Agroindustrial', 'Agricultura, silvicultura, pesca e veterinária', 'EaD', 'Bacharelado', 9767, 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 2923, 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Letras: Inglês', 'Educação', 'Presencial', 'Licenciatura', 3759, 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Biotecnologia', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 7812, 'FACULDADE UNIRB - MACEIO', 'AL', 'Maceió'),
('Matemática Aplicada E Computacional Com Habilitação Em Métodos Matemáticos', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 8543, 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Gestão De Produto', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 1112, 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Canto', 'Artes e humanidades', 'Presencial', 'Bacharelado', 2526, 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Engenharia Ambiental E Energias Renováveis', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 4480, 'CENTRO UNIVERSITÁRIO INTERNACIONAL', 'PR', 'Curitiba'),
('Ciências Fundamentais Para A Saúde', 'Saúde e bem-estar', 'Presencial', 'Bacharelado', 6322, 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Gestão Do Agronegócio', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 1130, 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Design Industrial', 'Artes e humanidades', 'EaD', 'Bacharelado', 1855, 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Estética', 'Serviços', 'Presencial', 'Bacharelado', 4506, 'UNIVERSIDADE DE BRASÍLIA', 'DF', 'Brasília'),
('Design Digital', 'Artes e humanidades', 'Presencial', 'Bacharelado', 4653, 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Estética E Cosmética', 'Serviços', 'EaD', 'Tecnólogo', 4445, 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Administração', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 8594, 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Toxicologia Ambiental', 'Ciências naturais, matemática e estatística', 'Presencial', 'Tecnólogo', 4934, 'FACULDADE DO LITORAL PARANAENSE', 'PR', 'Guaratuba'),
('Gestão Do Agronegócio', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 4102, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'Presencial', 'Licenciatura', 6590, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Têxtil E Moda', 'Engenharia, produção e construção', 'Presencial', 'Tecnólogo', 2075, 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DE PERNAMBUCO', 'PE', 'Recife'),
('Ciência De Dados E Inteligência Artificial', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Bacharelado', 6787, 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Letras - Línguas Adicionais Inglês, Espanhol E Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 5604, 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Gestão E Empreendedorismo', 'Educação', 'EaD', 'Licenciatura', 6021, 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Design Industrial', 'Artes e humanidades', 'Presencial', 'Bacharelado', 6933, 'FACULDADE BOOKPLAY', 'SP', 'Votuporanga'),
('Letras - Português-Inglês', 'Educação', 'EaD', 'Licenciatura', 5585, 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Biotecnologia', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 5105, 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Gestão De Produto', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 2495, 'Centro Universitário Uniasselvi de Brusque', 'SC', 'Brusque'),
('Educação Física', 'Educação', 'EaD', 'Licenciatura', 5969, 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Licenciatura Intercultural - Ciências Da Natureza', 'Educação', 'Presencial', 'Licenciatura', 1877, 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Música - Percussão', 'Artes e humanidades', 'EaD', 'Bacharelado', 1158, 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Inspeção De Equipamentos E De Soldagem', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 3033, 'FACULDADE SANTO ANTÔNIO', 'SP', 'Caçapava'),
('Letras - Português-Inglês', 'Educação', 'Presencial', 'Licenciatura', 6867, 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Engenharia Ambiental E Energias Renováveis', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 8564, 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Letras: Espanhol', 'Educação', 'EaD', 'Licenciatura', 3803, 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Letras - Árabe', 'Artes e humanidades', 'Presencial', 'Bacharelado', 7298, 'UNIVERSIDADE ESTADUAL DE SANTA CRUZ', 'BA', 'Ilhéus'),
('Gerontologia', 'Saúde e bem-estar', 'EaD', 'Tecnólogo', 1234, 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Letras Vernáculas - Português E Respectivas Literaturas', 'Educação', 'Presencial', 'Licenciatura', 8932, 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Música - Produção Musical', 'Artes e humanidades', 'Presencial', 'Bacharelado', 3047, 'FACULDADE ESAMC SOROCABA', 'SP', 'Sorocaba'),
('Manutenção De Aeronave De Asas Rotativas', 'Serviços', 'Presencial', 'Tecnólogo', 8547, 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Formação De Professores Indígenas', 'Educação', 'EaD', 'Licenciatura', 3624, 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Música - Violino E Viola', 'Artes e humanidades', 'EaD', 'Bacharelado', 7494, 'CENTRO UNIVERSITÁRIO DO PIAUÍ', 'PI', 'Teresina'),
('Interdisciplinar Em Ciência E Tecnologia', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 8215, 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Letras: Espanhol', 'Educação', 'Presencial', 'Licenciatura', 6511, 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Gestão Ambiental E Sustentabilidade', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 5063, 'CENTRO UNIVERSITÁRIO DA SERRA GAÚCHA', 'RS', 'Caxias do Sul'),
('Coaching E Mentoring', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 6483, 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Ciências Biológicas: Biofísica', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 7326, 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Letras - Língua E Literatura Japonesa', 'Educação', 'EaD', 'Licenciatura', 7002, 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Letras - Língua Portuguesa, Língua Inglesa E Suas Respectivas Literaturas', 'Educação', 'EaD', 'Licenciatura', 3402, 'Faculdade de Tecnologia e Ciências - FTC Parnamirim', 'RN', 'Parnamirim'),
('Desenvolvimento Rural E Gestão Agroindustrial', 'Agricultura, silvicultura, pesca e veterinária', 'Presencial', 'Bacharelado', 2240, 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'EaD', 'Bacharelado', 7935, 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Ciências Biológicas: Biofísica', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 8638, 'Faculdade Edufor de Salvador', 'BA', 'Salvador'),
('Toxicologia Ambiental', 'Ciências naturais, matemática e estatística', 'Presencial', 'Tecnólogo', 3272, 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Engenharia Mecânica Aeronáutica', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 2786, 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Ciências Humanas - Sociologia', 'Educação', 'EaD', 'Licenciatura', 7287, 'Fasul Educacional EaD', 'MG', 'São Lourenço'),
('Processos Escolares', 'Educação', 'Presencial', 'Tecnólogo', 5286, 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Gestão De Negócios', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 2268, 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Música - Percussão', 'Artes e humanidades', 'Presencial', 'Bacharelado', 1672, 'FACULDADE INTEGRADA DE SANTA MARIA', 'RS', 'Santa Maria'),
('Devops', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 4399, 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Alimentos', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 3558, 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Letras: Espanhol', 'Educação', 'Presencial', 'Licenciatura', 8974, 'FACULDADE ESTÁCIO DE SÁ DE CAMPO GRANDE', 'MS', 'Campo Grande'),
('Gestão Ambiental E Sustentabilidade', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 1485, 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Design Digital', 'Artes e humanidades', 'Presencial', 'Bacharelado', 6468, 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Administração', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 5093, 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Desenvolvimento De Produtos Plásticos', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 4686, 'Centro Universitário SATC', 'SC', 'Criciúma'),
('Produção Pesqueira', 'Agricultura, silvicultura, pesca e veterinária', 'Presencial', 'Tecnólogo', 8783, 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Canto', 'Artes e humanidades', 'Presencial', 'Bacharelado', 3224, 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Letras - Árabe', 'Artes e humanidades', 'Presencial', 'Bacharelado', 6856, 'FACULDADE ANHANGUERA DE SOBRAL', 'CE', 'Sobral'),
('Estética E Cosmética', 'Serviços', 'Presencial', 'Tecnólogo', 6413, 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Coaching', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 9762, 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Gestão E Empreendedorismo', 'Educação', 'Presencial', 'Licenciatura', 4535, 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Engenharia Naval', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 4793, 'FACULDADE ANHANGÜERA DE CAMPINAS', 'SP', 'Campinas'),
('Biotecnologia', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 9767, 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Línguas Estrangeiras Aplicadas Ao Multilinguismo E À Sociedade Da Informação', 'Artes e humanidades', 'EaD', 'Bacharelado', 4291, 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Engenharia Mecânica Aeronáutica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 3433, 'COLÉGIO TECNOLÓGICO DO ESTADO DE GOIÁS AGUINALDO DE CAMPOS N', 'GO', 'Catalão'),
('Línguas Estrangeiras Aplicadas Ao Multilinguismo E À Sociedade Da Informação', 'Artes e humanidades', 'Presencial', 'Bacharelado', 7514, 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Ciência De Dados E Inteligência Artificial', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Bacharelado', 8205, 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Engenharia Naval E Oceânica', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 7040, 'CENTRO UNIVERSITÁRIO DO SUL DE MINAS', 'MG', 'Varginha'),
('Coaching', 'Negócios, administração e direito', 'Presencial', 'Tecnólogo', 9272, 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Ciência Do Esporte', 'Saúde e bem-estar', 'Presencial', 'Bacharelado', 2669, 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Letras - Japonês', 'Educação', 'EaD', 'Licenciatura', 3677, 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Gestão E Empreendedorismo', 'Educação', 'Presencial', 'Licenciatura', 6057, 'Faculdade Marquês de Olinda', 'SP', 'Guarujá'),
('Matemática Computacional', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 7214, 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Letras - Latim', 'Educação', 'EaD', 'Licenciatura', 5726, 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Negócios Internacionais', 'Negócios, administração e direito', 'Presencial', 'Bacharelado', 5724, 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Ciências Biológicas: Biofísica', 'Ciências naturais, matemática e estatística', 'EaD', 'Bacharelado', 9691, 'CENTRO UNIVERSITARIO UNIVERSO BELO HORIZONTE', 'MG', 'Belo Horizonte'),
('Devops', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 5497, 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Bioinformática', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'Presencial', 'Tecnólogo', 4549, 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Engenharia Naval E Oceânica', 'Engenharia, produção e construção', 'Presencial', 'Bacharelado', 6784, 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Música - Violino E Viola', 'Artes e humanidades', 'Presencial', 'Bacharelado', 3265, 'FACULDADE LUSÓFONA DO RIO DE JANEIRO', 'RJ', 'São Gonçalo'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'EaD', 'Bacharelado', 8455, 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Processos Escolares', 'Educação', 'EaD', 'Tecnólogo', 3069, 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Música - Violino E Viola', 'Artes e humanidades', 'EaD', 'Bacharelado', 3774, 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Negócios Internacionais', 'Negócios, administração e direito', 'EaD', 'Bacharelado', 2881, 'ESCOLA SUPERIOR NACIONAL DE SEGUROS DE SÃO PAULO', 'SP', 'São Paulo'),
('Artes Visuais Com Habilitação Em Pintura', 'Artes e humanidades', 'Presencial', 'Bacharelado', 9816, 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Engenharia De Instrumentação, Automação E Robótica', 'Engenharia, produção e construção', 'EaD', 'Bacharelado', 2664, 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Ciências Exatas Com Habilitação Em Física', 'Educação', 'Presencial', 'Licenciatura', 4742, 'FACULDADE ESTÁCIO DE CANINDÉ', 'CE', 'Canindé'),
('Processos Escolares', 'Educação', 'Presencial', 'Tecnólogo', 3515, 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Letras: Espanhol', 'Educação', 'Presencial', 'Licenciatura', 9355, 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Biotecnologia', 'Ciências naturais, matemática e estatística', 'Presencial', 'Bacharelado', 2875, 'INSTITUTO SUPERIOR DE EDUCAÇÃO DO MUNICÍPIO DE ITAPERUNA', 'RJ', 'Itaperuna'),
('Comunicação Empresarial', 'Negócios, administração e direito', 'EaD', 'Tecnólogo', 2741, 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Letras - Português E Polonês', 'Educação', 'EaD', 'Licenciatura', 1094, 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Ciência Dos Dados', 'Computação e Tecnologias da Informação e Comunicação (TIC)', 'EaD', 'Tecnólogo', 1978, 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Design Visual', 'Artes e humanidades', 'Presencial', 'Bacharelado', 7292, 'Faculdade Doctum da Zona Norte de Juiz de Fora', 'MG', 'Juiz de Fora'),
('Estética', 'Serviços', 'EaD', 'Bacharelado', 5384, 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Ciência Do Esporte', 'Saúde e bem-estar', 'Presencial', 'Bacharelado', 6511, 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Letras - Língua E Literatura Japonesa', 'Educação', 'EaD', 'Licenciatura', 9625, 'FACULDADE JESUÍTA DE FILOSOFIA E TEOLOGIA', 'MG', 'Belo Horizonte'),
('Gestão E Empreendedorismo', 'Educação', 'EaD', 'Licenciatura', 5400, 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Têxtil E Moda', 'Engenharia, produção e construção', 'EaD', 'Tecnólogo', 1770, 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos'),
('Línguas Estrangeiras Aplicadas Ao Multilinguismo E À Sociedade Da Informação', 'Artes e humanidades', 'EaD', 'Bacharelado', 8945, 'Escola Superior São Judas de Guarulhos', 'SP', 'Guarulhos');